/**
 * Shared registry data extracted from AppBlueprintDiagram.
 * Consumable by AssetRegistryPanel, FeatureMapPanel, SystemArchitecturePanel, ModelCostSimulatorPanel.
 */

/** Maps blueprint node IDs to their associated feature flag IDs */
export const NODE_FEATURE_MAP: Record<string, string[]> = {
  "page:entry-detail": ["screenplay_viewer", "q2e_analytics", "voice_drift", "ai_review", "governance", "evidence_artifacts", "rewrite_lineage"],
  "page:submit": ["script_upload", "competition_entry"],
  "page:leaderboard": ["leaderboard"],
  "page:competition": ["competition_entry", "leaderboard"],
  "page:pricing": ["token_purchase"],
  "page:writer-profile": ["pen_name"],
  "fn:ai-judge": ["ai_score"],
  "fn:ai-compare": ["deep_analysis"],
  "fn:voice-drift": ["voice_drift"],
  "fn:rewrite-selection": ["rewrite_lineage"],
  "fn:generate-artifact": ["evidence_artifacts"],
  "fn:spend-tokens": ["token_purchase"],
  "fn:transfer-tokens": ["token_transfer"],
  "fn:organize-brain-dump": ["brain_dump"],
  "fn:suggest-character-diamond": ["character_diamond_suggest"],
  "fn:embed-character": ["character_drift_embedding"],
  "fn:verify-character-identity": ["identity_engine"],
  "fn:rollback-character-diamond": ["character_rollback"],
  "page:brain-dump": ["brain_dump"],
  "comp:character-diamond": ["character_diamond_suggest", "character_drift_embedding", "identity_engine"],
  "comp:governance": ["governance"],
  "comp:evidence": ["evidence_artifacts"],
  "comp:feature-voting": ["token_purchase"],
  "comp:wallet": ["token_purchase"],
  "ctx:platform": ["ai_score", "deep_analysis", "screenplay_viewer"],
};

/** Supported Lovable AI Gateway models */
export const LOVABLE_MODELS = [
  "google/gemini-2.5-flash",
  "google/gemini-2.5-flash-lite",
  "google/gemini-2.5-pro",
  "google/gemini-3-flash-preview",
  "google/gemini-3.1-pro-preview",
  "google/gemini-3-pro-image-preview",
  "google/gemini-3.1-flash-image-preview",
  "openai/gpt-5",
  "openai/gpt-5-mini",
  "openai/gpt-5-nano",
  "openai/gpt-5.2",
] as const;

/** Cost per 1K tokens (in cents) for supported models */
export const COST_PER_1K: Record<string, { input: number; output: number }> = {
  "google/gemini-2.5-flash": { input: 0.15, output: 0.60 },
  "google/gemini-3-flash-preview": { input: 0.15, output: 0.60 },
  "google/gemini-2.5-pro": { input: 1.25, output: 10.00 },
  "google/gemini-3.1-pro-preview": { input: 1.25, output: 10.00 },
  "openai/gpt-5-mini": { input: 0.40, output: 1.60 },
  "openai/gpt-5": { input: 2.50, output: 10.00 },
};

export const DEFAULT_MODEL = "google/gemini-3-flash-preview";

export interface RegistryEntry {
  file: string;
  category: string;
  label: string;
}

/** Full codebase file registry with categories */
export const CODEBASE_REGISTRY: RegistryEntry[] = [
  // Pages
  {file:"src/pages/Index.tsx",category:"page",label:"Index"},{file:"src/pages/Auth.tsx",category:"page",label:"Auth"},{file:"src/pages/AICompetition.tsx",category:"page",label:"AI Competition"},{file:"src/pages/BadgeCatalog.tsx",category:"page",label:"Badge Catalog"},{file:"src/pages/DemoEntry.tsx",category:"page",label:"Demo Entry"},{file:"src/pages/EntryDetail.tsx",category:"page",label:"Entry Detail"},{file:"src/pages/FAQPage.tsx",category:"page",label:"FAQ"},{file:"src/pages/FestivalProfile.tsx",category:"page",label:"Festival Profile"},{file:"src/pages/FutureReaders.tsx",category:"page",label:"Future Readers"},{file:"src/pages/GodMode.tsx",category:"page",label:"God Mode"},{file:"src/pages/HowItWorks.tsx",category:"page",label:"How It Works"},{file:"src/pages/Leaderboard.tsx",category:"page",label:"Leaderboard"},{file:"src/pages/MySubmissions.tsx",category:"page",label:"My Submissions"},{file:"src/pages/NotFound.tsx",category:"page",label:"Not Found"},{file:"src/pages/PlatformPage.tsx",category:"page",label:"Platform"},{file:"src/pages/Pricing.tsx",category:"page",label:"Pricing"},{file:"src/pages/ResetPassword.tsx",category:"page",label:"Reset Password"},{file:"src/pages/SubmissionPortal.tsx",category:"page",label:"Submission Portal"},{file:"src/pages/WriterProfile.tsx",category:"page",label:"Writer Profile"},
  {file:"src/pages/Advertise.tsx",category:"page",label:"Advertise"},{file:"src/pages/NewsPage.tsx",category:"page",label:"News"},{file:"src/pages/PublicProject.tsx",category:"page",label:"Public Project"},{file:"src/pages/PublicRead.tsx",category:"page",label:"Public Read"},{file:"src/pages/PublicWriter.tsx",category:"page",label:"Public Writer"},{file:"src/pages/QiList.tsx",category:"page",label:"QI List"},{file:"src/pages/Seasons.tsx",category:"page",label:"Seasons"},{file:"src/pages/SharedEntry.tsx",category:"page",label:"Shared Entry"},{file:"src/pages/StudioPortal.tsx",category:"page",label:"Studio Portal"},{file:"src/pages/MySubscriptionsPage.tsx",category:"page",label:"My Subscriptions"},{file:"src/pages/Unsubscribe.tsx",category:"page",label:"Unsubscribe"},

  // Components
  {file:"src/components/AIJudgingSection.tsx",category:"component",label:"AI Judging Section"},{file:"src/components/AILawTimeline.tsx",category:"component",label:"AI Law Timeline"},{file:"src/components/AccessGate.tsx",category:"component",label:"Access Gate"},{file:"src/components/AchievementsPanel.tsx",category:"component",label:"Achievements Panel"},{file:"src/components/ActiveSubmissions.tsx",category:"component",label:"Active Submissions"},{file:"src/components/AiFieldBadge.tsx",category:"component",label:"AI Field Badge"},{file:"src/components/BottomBar.tsx",category:"component",label:"Bottom Bar"},{file:"src/components/ChangelogSection.tsx",category:"component",label:"Changelog Section"},{file:"src/components/ClosedTrialApplication.tsx",category:"component",label:"Closed Trial App"},{file:"src/components/ComingSoonSection.tsx",category:"component",label:"Coming Soon"},{file:"src/components/DemoScreenplaySection.tsx",category:"component",label:"Demo Screenplay"},{file:"src/components/EvidenceArtifactsPanel.tsx",category:"component",label:"Evidence Artifacts"},{file:"src/components/FeatureSubscribeModal.tsx",category:"component",label:"Feature Subscribe Modal"},{file:"src/components/FeatureVoting.tsx",category:"component",label:"Feature Voting"},{file:"src/components/FloatingWallet.tsx",category:"component",label:"Floating Wallet"},{file:"src/components/Footer.tsx",category:"component",label:"Footer"},{file:"src/components/GovernancePanel.tsx",category:"component",label:"Governance Panel"},{file:"src/components/GovernanceStatusBadges.tsx",category:"component",label:"Governance Badges"},{file:"src/components/IPRiskAssessment.tsx",category:"component",label:"IP Risk Assessment"},{file:"src/components/Layout.tsx",category:"component",label:"Layout"},{file:"src/components/NavLink.tsx",category:"component",label:"NavLink"},{file:"src/components/Navbar.tsx",category:"component",label:"Navbar"},{file:"src/components/RoadmapPanel.tsx",category:"component",label:"Roadmap Panel"},{file:"src/components/ScoreChart.tsx",category:"component",label:"Score Chart"},{file:"src/components/ScoreDiff.tsx",category:"component",label:"Score Diff"},{file:"src/components/Section.tsx",category:"component",label:"Section"},{file:"src/components/SubmissionProgressBar.tsx",category:"component",label:"Submission Progress"},{file:"src/components/TokenEconomyPanel.tsx",category:"component",label:"Token Economy"},{file:"src/components/TokenPurchaseModal.tsx",category:"component",label:"Token Purchase Modal"},{file:"src/components/TokenTransferModal.tsx",category:"component",label:"Token Transfer Modal"},{file:"src/components/TransactionHistory.tsx",category:"component",label:"Transaction History"},
  {file:"src/components/CollaborationPanel.tsx",category:"component",label:"Collaboration Panel"},{file:"src/components/CollapsibleSection.tsx",category:"component",label:"Collapsible Section"},{file:"src/components/DevelopmentPipelinePanel.tsx",category:"component",label:"Dev Pipeline Panel"},{file:"src/components/DevelopmentTrajectoryPanel.tsx",category:"component",label:"Dev Trajectory Panel"},{file:"src/components/JudgingTransparency.tsx",category:"component",label:"Judging Transparency"},{file:"src/components/LineageGraph.tsx",category:"component",label:"Lineage Graph"},{file:"src/components/NarrativeContinuityPanel.tsx",category:"component",label:"Narrative Continuity"},{file:"src/components/NotificationBell.tsx",category:"component",label:"Notification Bell"},{file:"src/components/PastWinnersSection.tsx",category:"component",label:"Past Winners"},{file:"src/components/PitchPackageBuilder.tsx",category:"component",label:"Pitch Package Builder"},{file:"src/components/ProductionReadinessPanel.tsx",category:"component",label:"Production Readiness"},{file:"src/components/ProjectIntelligenceDashboard.tsx",category:"component",label:"Project Intelligence"},{file:"src/components/ProjectMemoryGraph.tsx",category:"component",label:"Project Memory Graph"},{file:"src/components/ProvenanceLineagePanel.tsx",category:"component",label:"Provenance Lineage"},{file:"src/components/ReviewWorkflowPanel.tsx",category:"component",label:"Review Workflow"},{file:"src/components/ShareLinksPanel.tsx",category:"component",label:"Share Links"},{file:"src/components/StoryWorldPanel.tsx",category:"component",label:"Story World"},{file:"src/components/TesterFeedbackButton.tsx",category:"component",label:"Tester Feedback"},{file:"src/components/TrustReport.tsx",category:"component",label:"Trust Report"},

  // Screenplay components
  {file:"src/components/screenplay/AnalysisTabs.tsx",category:"component",label:"Analysis Tabs"},{file:"src/components/screenplay/FreeScreenplayPreview.tsx",category:"component",label:"Free Screenplay Preview"},{file:"src/components/screenplay/ModelComparePanel.tsx",category:"component",label:"Model Compare"},{file:"src/components/screenplay/NotesPanel.tsx",category:"component",label:"Notes Panel"},{file:"src/components/screenplay/PageNavigation.tsx",category:"component",label:"Page Navigation"},{file:"src/components/screenplay/PinnableModule.tsx",category:"component",label:"Pinnable Module"},{file:"src/components/screenplay/ProjectDevPanel.tsx",category:"component",label:"Project Dev Panel"},{file:"src/components/screenplay/RewriteLineageTree.tsx",category:"component",label:"Rewrite Lineage"},{file:"src/components/screenplay/RewriteToolbar.tsx",category:"component",label:"Rewrite Toolbar"},{file:"src/components/screenplay/ScreenplayRenderer.tsx",category:"component",label:"Screenplay Renderer"},{file:"src/components/screenplay/ScriptStatsCard.tsx",category:"component",label:"Script Stats"},{file:"src/components/screenplay/StoryDevTab.tsx",category:"component",label:"Story Dev Tab"},
  {file:"src/components/screenplay/AdaptationPathwayPanel.tsx",category:"component",label:"Adaptation Pathway"},{file:"src/components/screenplay/CharacterVoicePanel.tsx",category:"component",label:"Character Voice"},{file:"src/components/screenplay/DraftComparisonPanel.tsx",category:"component",label:"Draft Comparison"},{file:"src/components/screenplay/NarrativeIntelligencePanel.tsx",category:"component",label:"Narrative Intelligence"},{file:"src/components/screenplay/SceneHeatmap.tsx",category:"component",label:"Scene Heatmap"},{file:"src/components/screenplay/WordDiffLineView.tsx",category:"component",label:"Word Diff Line View"},{file:"src/components/screenplay/RewriteSuggestions.tsx",category:"component",label:"Rewrite Suggestions"},

  // Entry components
  {file:"src/components/entry/DraftHistoryRow.tsx",category:"component",label:"Draft History Row"},{file:"src/components/entry/Q2ESection.tsx",category:"component",label:"Q2E Section"},{file:"src/components/entry/StabilityCard.tsx",category:"component",label:"Stability Card"},{file:"src/components/entry/VoiceDriftSection.tsx",category:"component",label:"Voice Drift Section"},

  // Wallet / Studio / Submission / Writer / Platform components
  {file:"src/components/wallet/WalletDataDeletion.tsx",category:"component",label:"Wallet Data Deletion"},{file:"src/components/wallet/WalletSubscriptions.tsx",category:"component",label:"Wallet Subscriptions"},
  {file:"src/components/studio/BatchResultsSummary.tsx",category:"component",label:"Batch Results Summary"},{file:"src/components/studio/BatchUploadPanel.tsx",category:"component",label:"Batch Upload Panel"},
  {file:"src/components/submission/SubmissionAuthGate.tsx",category:"component",label:"Submission Auth Gate"},{file:"src/components/submission/SubmissionStatusBadge.tsx",category:"component",label:"Submission Status Badge"},{file:"src/components/submission/SubmissionStepper.tsx",category:"component",label:"Submission Stepper"},
  {file:"src/components/writer/CareerDevelopmentTab.tsx",category:"component",label:"Career Dev Tab"},{file:"src/components/writer/ProfileCompletenessCard.tsx",category:"component",label:"Profile Completeness"},{file:"src/components/writer/ProjectMaturityBadge.tsx",category:"component",label:"Project Maturity Badge"},
  {file:"src/components/platform/DevStatusDot.tsx",category:"component",label:"Dev Status Dot"},{file:"src/components/platform/DeveloperPanel.tsx",category:"component",label:"Developer Panel"},{file:"src/components/platform/FeatureGate.tsx",category:"component",label:"Feature Gate"},{file:"src/components/platform/FeatureTierGate.tsx",category:"component",label:"Feature Tier Gate"},{file:"src/components/platform/PlatformSwitcher.tsx",category:"component",label:"Platform Switcher"},

  // Admin panels
  {file:"src/components/admin/AIOverviewPanel.tsx",category:"admin",label:"AI Overview Panel"},{file:"src/components/admin/AccessManagementPanel.tsx",category:"admin",label:"Access Mgmt Panel"},{file:"src/components/admin/ActivityLogPanel.tsx",category:"admin",label:"Activity Log Panel"},{file:"src/components/admin/AdSpaceManagementPanel.tsx",category:"admin",label:"Ad Space Mgmt"},{file:"src/components/admin/ArtifactMonitoringPanel.tsx",category:"admin",label:"Artifact Monitoring"},{file:"src/components/admin/CostMonitorPanel.tsx",category:"admin",label:"Cost Monitor"},{file:"src/components/admin/DataDeletionPanel.tsx",category:"admin",label:"Data Deletion"},{file:"src/components/admin/DeveloperLogPanel.tsx",category:"admin",label:"Developer Log"},{file:"src/components/admin/DocumentEditor.tsx",category:"admin",label:"Document Editor"},{file:"src/components/admin/DocumentsPanel.tsx",category:"admin",label:"Documents Panel"},{file:"src/components/admin/EntryManagementPanel.tsx",category:"admin",label:"Entry Mgmt"},{file:"src/components/admin/FeatureSubscriptionAdminPanel.tsx",category:"admin",label:"Feature Sub Admin"},{file:"src/components/admin/FestivalManagementPanel.tsx",category:"admin",label:"Festival Mgmt"},{file:"src/components/admin/GodModeSearch.tsx",category:"admin",label:"God Mode Search"},{file:"src/components/admin/GovernanceAuditPanel.tsx",category:"admin",label:"Governance Audit"},{file:"src/components/admin/GovernanceDashboardCard.tsx",category:"admin",label:"Governance Card"},{file:"src/components/admin/HealthDashboardPanel.tsx",category:"admin",label:"Health Dashboard"},{file:"src/components/admin/InlineJudgeConfig.tsx",category:"admin",label:"Inline Judge Config"},{file:"src/components/admin/JudgeConfigPanel.tsx",category:"admin",label:"Judge Config Panel"},{file:"src/components/admin/JudgeUsagePanel.tsx",category:"admin",label:"Judge Usage Panel"},{file:"src/components/admin/LandingPagePanel.tsx",category:"admin",label:"Landing Page Panel"},{file:"src/components/admin/ModuleManagementPanel.tsx",category:"admin",label:"Module Mgmt"},{file:"src/components/admin/SiteControlsPanel.tsx",category:"admin",label:"Site Controls"},{file:"src/components/admin/SubscriptionManagementPanel.tsx",category:"admin",label:"Subscription Mgmt"},{file:"src/components/admin/SwitchboardPanel.tsx",category:"admin",label:"Switchboard Panel"},{file:"src/components/admin/SystemArchitecturePanel.tsx",category:"admin",label:"System Architecture"},{file:"src/components/admin/SystemAuditPanel.tsx",category:"admin",label:"System Audit"},{file:"src/components/admin/UsageAnalyticsPanel.tsx",category:"admin",label:"Usage Analytics"},
  {file:"src/components/admin/AIRoutingPanel.tsx",category:"admin",label:"AI Routing"},{file:"src/components/admin/AccessChangesLogPanel.tsx",category:"admin",label:"Access Changes Log"},{file:"src/components/admin/AssetRegistryPanel.tsx",category:"admin",label:"Asset Registry"},{file:"src/components/admin/BuildEconomicsCard.tsx",category:"admin",label:"Build Economics"},{file:"src/components/admin/CharacterVoiceOverviewPanel.tsx",category:"admin",label:"Character Voice Overview"},{file:"src/components/admin/CollaborationOverviewPanel.tsx",category:"admin",label:"Collaboration Overview"},{file:"src/components/admin/DevelopmentPipelineOverviewPanel.tsx",category:"admin",label:"Dev Pipeline Overview"},{file:"src/components/admin/EventEconomicsPanel.tsx",category:"admin",label:"Event Economics"},{file:"src/components/admin/FeatureMapPanel.tsx",category:"admin",label:"Feature Map"},{file:"src/components/admin/KnowledgePanel.tsx",category:"admin",label:"Knowledge Panel"},{file:"src/components/admin/LighthouseAuditPanel.tsx",category:"admin",label:"Lighthouse Audit"},{file:"src/components/admin/MemoryGraphOverviewPanel.tsx",category:"admin",label:"Memory Graph Overview"},{file:"src/components/admin/ModelCostSimulatorPanel.tsx",category:"admin",label:"Model Cost Simulator"},{file:"src/components/admin/ModelHealthPanel.tsx",category:"admin",label:"Model Health"},{file:"src/components/admin/NewsManagementPanel.tsx",category:"admin",label:"News Management"},{file:"src/components/admin/NotificationsPanel.tsx",category:"admin",label:"Notifications"},{file:"src/components/admin/ProFormaBudget.tsx",category:"admin",label:"Pro Forma Budget"},{file:"src/components/admin/ProFormaBudgetSection.tsx",category:"admin",label:"Pro Forma Budget Section"},{file:"src/components/admin/ProfitMarginsPanel.tsx",category:"admin",label:"Profit Margins"},{file:"src/components/admin/ProjectIntelligenceOverviewPanel.tsx",category:"admin",label:"Project Intelligence Overview"},{file:"src/components/admin/ReferralTrackingPanel.tsx",category:"admin",label:"Referral Tracking"},{file:"src/components/admin/SeasonZeroOpsPanel.tsx",category:"admin",label:"Season Zero Ops"},{file:"src/components/admin/SiteAnalyticsPanel.tsx",category:"admin",label:"Site Analytics"},{file:"src/components/admin/StabilityOverviewPanel.tsx",category:"admin",label:"Stability Overview"},{file:"src/components/admin/SubscriptionUsageAnalyticsPanel.tsx",category:"admin",label:"Subscription Usage Analytics"},{file:"src/components/admin/TitleLoglineHistoryPanel.tsx",category:"admin",label:"Title Logline History"},{file:"src/components/admin/TrustOverviewPanel.tsx",category:"admin",label:"Trust Overview"},{file:"src/components/admin/UserRequestsPanel.tsx",category:"admin",label:"User Requests"},

  // AI overview sub-components
  {file:"src/components/admin/ai-overview/FeatureTable.tsx",category:"admin",label:"AI Feature Table"},{file:"src/components/admin/ai-overview/ModelBreakdown.tsx",category:"admin",label:"AI Model Breakdown"},{file:"src/components/admin/ai-overview/Sparkline.tsx",category:"admin",label:"AI Sparkline"},{file:"src/components/admin/ai-overview/SummaryCards.tsx",category:"admin",label:"AI Summary Cards"},

  // Edge functions
  {file:"supabase/functions/add-tokens/index.ts",category:"function",label:"add-tokens"},{file:"supabase/functions/ai-compare/index.ts",category:"function",label:"ai-compare"},{file:"supabase/functions/ai-judge/index.ts",category:"function",label:"ai-judge"},{file:"supabase/functions/auto-audit/index.ts",category:"function",label:"auto-audit"},{file:"supabase/functions/export-document/index.ts",category:"function",label:"export-document"},{file:"supabase/functions/export-evidence-bundle/index.ts",category:"function",label:"export-evidence-bundle"},{file:"supabase/functions/generate-artifact/index.ts",category:"function",label:"generate-artifact"},{file:"supabase/functions/generate-script/index.ts",category:"function",label:"generate-script"},{file:"supabase/functions/legal-summary/index.ts",category:"function",label:"legal-summary"},{file:"supabase/functions/manage-feature-subscription/index.ts",category:"function",label:"manage-feature-subscription"},{file:"supabase/functions/notify-admin-demo-request/index.ts",category:"function",label:"notify-admin-demo-request"},{file:"supabase/functions/notify-subsystem-alert/index.ts",category:"function",label:"notify-subsystem-alert"},{file:"supabase/functions/notify-trial-application/index.ts",category:"function",label:"notify-trial-application"},{file:"supabase/functions/parse-screenplay/index.ts",category:"function",label:"parse-screenplay"},{file:"supabase/functions/renew-subscriptions/index.ts",category:"function",label:"renew-subscriptions"},{file:"supabase/functions/rewrite-selection/index.ts",category:"function",label:"rewrite-selection"},{file:"supabase/functions/seed-demo-profiles/index.ts",category:"function",label:"seed-demo-profiles"},{file:"supabase/functions/seed-filmstack/index.ts",category:"function",label:"seed-filmstack"},{file:"supabase/functions/seed-governance-demo/index.ts",category:"function",label:"seed-governance-demo"},{file:"supabase/functions/spend-tokens/index.ts",category:"function",label:"spend-tokens"},{file:"supabase/functions/transfer-tokens/index.ts",category:"function",label:"transfer-tokens"},{file:"supabase/functions/voice-drift/index.ts",category:"function",label:"voice-drift"},
  {file:"supabase/functions/activate-pro-tokens/index.ts",category:"function",label:"activate-pro-tokens"},{file:"supabase/functions/auth-email-hook/index.ts",category:"function",label:"auth-email-hook"},{file:"supabase/functions/handle-email-suppression/index.ts",category:"function",label:"handle-email-suppression"},{file:"supabase/functions/handle-email-unsubscribe/index.ts",category:"function",label:"handle-email-unsubscribe"},{file:"supabase/functions/preview-transactional-email/index.ts",category:"function",label:"preview-transactional-email"},{file:"supabase/functions/process-batch/index.ts",category:"function",label:"process-batch"},{file:"supabase/functions/process-email-queue/index.ts",category:"function",label:"process-email-queue"},{file:"supabase/functions/send-transactional-email/index.ts",category:"function",label:"send-transactional-email"},{file:"supabase/functions/withdraw-entry/index.ts",category:"function",label:"withdraw-entry"},{file:"supabase/functions/suggest-rewrites/index.ts",category:"function",label:"suggest-rewrites"},{file:"supabase/functions/ai-analyze-reports/index.ts",category:"function",label:"ai-analyze-reports"},{file:"supabase/functions/model-health-check/index.ts",category:"function",label:"model-health-check"},

  // Shared libs
  {file:"supabase/functions/_shared/ai-router.ts",category:"lib",label:"AI Router (shared)"},{file:"supabase/functions/_shared/governance.ts",category:"lib",label:"Governance (shared)"},

  // Contexts
  {file:"src/contexts/PlatformContext.tsx",category:"context",label:"Platform Context"},{file:"src/contexts/SubscriptionContext.tsx",category:"context",label:"Subscription Context"},{file:"src/contexts/SiteSettingsContext.tsx",category:"context",label:"Site Settings Context"},

  // Hooks
  {file:"src/hooks/use-mobile.tsx",category:"hook",label:"useMobile"},{file:"src/hooks/use-toast.ts",category:"hook",label:"useToast"},{file:"src/hooks/useAuth.tsx",category:"hook",label:"useAuth"},{file:"src/hooks/useHighlights.ts",category:"hook",label:"useHighlights"},{file:"src/hooks/useLoginRateLimit.ts",category:"hook",label:"useLoginRateLimit"},{file:"src/hooks/useSiteSettings.ts",category:"hook",label:"useSiteSettings"},{file:"src/hooks/useWallet.tsx",category:"hook",label:"useWallet"},{file:"src/hooks/useHashTab.ts",category:"hook",label:"useHashTab"},

  // Libs
  {file:"src/lib/diff.ts",category:"lib",label:"diff"},{file:"src/lib/fountain-paginator.ts",category:"lib",label:"fountain-paginator"},{file:"src/lib/fountain-parser.ts",category:"lib",label:"fountain-parser"},{file:"src/lib/iconMap.ts",category:"lib",label:"iconMap"},{file:"src/lib/plans.ts",category:"lib",label:"plans"},{file:"src/lib/similarity.ts",category:"lib",label:"similarity"},{file:"src/lib/subsystems.ts",category:"lib",label:"subsystems"},{file:"src/lib/utils.ts",category:"lib",label:"utils"},{file:"src/lib/wallet.ts",category:"lib",label:"wallet"},{file:"src/lib/character.ts",category:"lib",label:"character"},{file:"src/lib/evidence-schema.ts",category:"lib",label:"evidence-schema"},{file:"src/lib/knowledge.ts",category:"lib",label:"knowledge"},{file:"src/lib/score-utils.ts",category:"lib",label:"score-utils"},{file:"src/lib/stability.ts",category:"lib",label:"stability"},{file:"src/lib/filmstack.ts",category:"lib",label:"filmstack"},{file:"src/lib/blueprint-registry.ts",category:"lib",label:"blueprint-registry"},{file:"src/lib/export/exportEvidenceBundle.ts",category:"lib",label:"exportEvidenceBundle"},{file:"src/lib/export/exportEvidencePDF.ts",category:"lib",label:"exportEvidencePDF"},
];

/** Maps blueprint node IDs to database table names */
export const DATA_TABLE_MAP: Record<string, string> = {
  "data:entries":"entries","data:scores":"scores","data:competitions":"competitions","data:profiles":"profiles","data:wallets":"token_wallets","data:transactions":"wallet_transactions","data:badges":"user_badges","data:genres":"user_genre_stats","data:governance":"governance_events","data:artifacts":"artifacts","data:versions":"screenplay_versions","data:influence":"influence_scores","data:highlights":"screenplay_highlights","data:ai-usage":"ai_usage_log","data:eval-runs":"evaluation_runs","data:judge-config":"competition_judge_config","data:judge-usage":"judge_usage_log","data:feature-configs":"feature_configs","data:feature-usage":"feature_usage_log","data:feature-votes":"feature_votes","data:feature-subs":"feature_subscriptions","data:roadmap":"feature_roadmap","data:access-grants":"access_grants","data:access-requests":"access_requests","data:invites":"pending_invites","data:festivals":"festivals","data:seasons":"seasons","data:ad-slots":"festival_ad_slots","data:ad-analytics":"ad_slot_analytics","data:subscriptions":"subscriptions","data:purchases":"purchases","data:sub-changes":"subscription_changes","data:site-settings":"site_settings","data:audit-log":"audit_log","data:docs":"business_documents","data:doc-versions":"document_versions","data:notifications":"user_notifications","data:deletion-requests":"data_deletion_requests","data:demo-requests":"demo_access_requests","data:trial-apps":"closed_trial_applications","data:waitlist":"launch_waitlist","data:studio-inquiries":"studio_inquiries","data:module-configs":"module_configs","data:user-module-grants":"user_module_grants","data:user-feature-grants":"user_feature_grants","data:roles":"user_roles","data:voice-drift":"voice_drift_analysis","data:quotients":"script_quotients","data:artifact-metrics":"artifact_metrics","data:provenance-nodes":"provenance_nodes","data:provenance-edges":"provenance_edges","data:landing-config":"landing_page_config","data:system-audits":"system_audits","data:upload-bonuses":"upload_bonuses_claimed","data:email-log":"email_send_log","data:email-state":"email_send_state","data:email-unsub-tokens":"email_unsubscribe_tokens","data:suppressed-emails":"suppressed_emails","data:news":"news_articles","data:batch-jobs":"batch_jobs","data:batch-items":"batch_items","data:collab-events":"collaboration_events","data:grading-reports":"grading_reports","data:knowledge-docs":"knowledge_documents","data:knowledge-concepts":"knowledge_concepts","data:knowledge-links":"knowledge_links","data:ai-models":"ai_models","data:model-prefs":"model_preferences",
};
