/**
 * Shared jsPDF renderer — Cinema Aurea system.
 *
 * Every client-side PDF export must build its cover with `renderTitleBand()`
 * and its footer with `drawFooter()` so submission receipts, evidence
 * certificates, outlines, parity agreements, and rubric summaries share one
 * visual identity: a dark cover band with a gold display title, muted
 * subtitle, and quiet footer.
 *
 * All layout numbers, palette entries, font sizes, and stroke weights live
 * in the single `CINEMA_AUREA_SETTINGS` object below. Edit that object (or
 * call `configureCinemaAurea(partial)` at app boot) to restyle every PDF
 * export at once — do not hard-code new values inside helpers.
 *
 * Coordinate model: helpers work in whatever unit the passed `jsPDF` doc uses
 * (in, pt, mm) by converting internal pt offsets through `scaleFactor`. That
 * lets every existing exporter keep its own unit system while sharing this
 * cover.
 */

import { jsPDF } from "jspdf";
export type { jsPDF };

// ─── Types ────────────────────────────────────────────────────────────────

export type RGB = readonly [number, number, number];

export interface CinemaAureaPalette {
  /** Cover band background — near-black cinema. */
  bandBg: RGB;
  /** Primary gold — display type and hairline accents. */
  gold: RGB;
  /** Subtitle text on dark band. */
  subtitle: RGB;
  /** Body copy on white. */
  body: RGB;
  /** Muted metadata / footer text. */
  muted: RGB;
  /** Divider rule on light backgrounds. */
  rule: RGB;
}

/** All layout numbers are expressed in typographic points (pt). */
export interface CinemaAureaMetrics {
  /** Uniform page margin used by cover, footer, and rules. */
  marginPt: number;
  /** Vertical whitespace between the band and the first body element. */
  bodyGapPt: number;
  /** Footer baseline distance from bottom edge. */
  footerOffsetPt: number;
  /** Distance between page top and the eyebrow baseline. */
  bandEyebrowYPt: number;
  /** Distance between page top and the title baseline. */
  bandTitleYPt: number;
  /** Distance between page top and the subtitle baseline. */
  bandSubtitleYPt: number;
  /** Total height of the dark cover band. */
  bandHeightPt: number;
}

export interface CinemaAureaTypography {
  /** Font family used for every string drawn by shared helpers. */
  fontFamily: "helvetica" | "times" | "courier";
  eyebrowSizePt: number;
  titleSizePt: number;
  subtitleSizePt: number;
  bodySizePt: number;
  footerSizePt: number;
  /** Default section-heading size for `drawSectionHeading()`. */
  sectionHeadingSizePt: number;
}

export interface CinemaAureaStrokes {
  /** Gold hairline under the band and under section headings. */
  accentPt: number;
  /** Muted rule between body sections. */
  rulePt: number;
}

export interface CinemaAureaSettings {
  palette: CinemaAureaPalette;
  metrics: CinemaAureaMetrics;
  typography: CinemaAureaTypography;
  strokes: CinemaAureaStrokes;
  /** Default left-side footer attribution. */
  footerBrand: string;
}

// ─── Default settings ─────────────────────────────────────────────────────

const DEFAULT_SETTINGS: CinemaAureaSettings = {
  palette: {
    bandBg: [15, 17, 22],
    gold: [212, 175, 55],
    subtitle: [210, 210, 210],
    body: [30, 30, 30],
    muted: [120, 120, 120],
    rule: [200, 200, 200],
  },
  metrics: {
    marginPt: 48,
    bodyGapPt: 24,
    footerOffsetPt: 24,
    bandEyebrowYPt: 22,
    bandTitleYPt: 42,
    bandSubtitleYPt: 62,
    bandHeightPt: 80,
  },
  typography: {
    fontFamily: "helvetica",
    eyebrowSizePt: 8,
    titleSizePt: 18,
    subtitleSizePt: 10,
    bodySizePt: 10,
    footerSizePt: 8,
    sectionHeadingSizePt: 11,
  },
  strokes: {
    accentPt: 0.6,
    rulePt: 0.3,
  },
  footerBrand: "Generated by Can I Screenwrite — caniscreenwrite.com",
};

// Deep-cloned mutable copy so overrides at runtime don't leak into DEFAULT.
let ACTIVE: CinemaAureaSettings = deepClone(DEFAULT_SETTINGS);

/**
 * Live-read the current Cinema Aurea settings. Every helper in this module
 * calls this — callers can read it too when composing their own layout.
 */
export function getCinemaAureaSettings(): CinemaAureaSettings {
  return ACTIVE;
}

/**
 * Merge a partial override into the active Cinema Aurea settings. Any
 * omitted subsection keeps the current value. Use once at app boot (or in
 * a theming layer) to restyle every PDF export in the app consistently.
 */
export function configureCinemaAurea(partial: DeepPartial<CinemaAureaSettings>): CinemaAureaSettings {
  ACTIVE = mergeDeep(ACTIVE, partial);
  return ACTIVE;
}

/** Reset to shipped defaults — primarily for tests. */
export function resetCinemaAureaSettings(): CinemaAureaSettings {
  ACTIVE = deepClone(DEFAULT_SETTINGS);
  return ACTIVE;
}

/**
 * Legacy palette export retained for existing callers that import
 * `CINEMA_AUREA.gold` etc. New code should call `getCinemaAureaSettings()`
 * so runtime overrides via `configureCinemaAurea` are honored.
 */
export const CINEMA_AUREA: CinemaAureaPalette = new Proxy(
  {} as CinemaAureaPalette,
  {
    get(_t, prop: string) {
      const p = ACTIVE.palette as unknown as Record<string, RGB>;
      return p[prop];
    },
    ownKeys() {
      return Object.keys(ACTIVE.palette);
    },
    getOwnPropertyDescriptor(_t, prop: string) {
      if (prop in ACTIVE.palette) {
        return { enumerable: true, configurable: true, value: (ACTIVE.palette as any)[prop] };
      }
      return undefined;
    },
  },
);

// ─── Low-level helpers ────────────────────────────────────────────────────

const setFill = (doc: jsPDF, c: RGB) => doc.setFillColor(c[0], c[1], c[2]);
const setText = (doc: jsPDF, c: RGB) => doc.setTextColor(c[0], c[1], c[2]);
const setDraw = (doc: jsPDF, c: RGB) => doc.setDrawColor(c[0], c[1], c[2]);

/** Convert a point value to the doc's active unit (in/pt/mm). */
export function ptToUnit(doc: jsPDF, pt: number): number {
  // jsPDF exposes scaleFactor = points per user unit.
  const sf = (doc.internal as unknown as { scaleFactor: number }).scaleFactor;
  return pt / sf;
}

// ─── Title band ───────────────────────────────────────────────────────────
export interface TitleBandSpec {
  /** Big display title in gold. */
  title: string;
  /** Optional muted subtitle line under the title. */
  subtitle?: string;
  /** Optional tiny uppercase eyebrow above the title. */
  eyebrow?: string;
}

export interface TitleBandResult {
  /** Y position (doc units) where the caller's body content should start. */
  nextY: number;
  /** Bottom edge of the dark band, in doc units. */
  bandBottom: number;
}

/**
 * Paint the shared cover band at y=0 and return the y-offset where body
 * content should resume. Caller is expected to keep drawing below `nextY`
 * using its own layout logic.
 */
export function renderTitleBand(doc: jsPDF, spec: TitleBandSpec): TitleBandResult {
  const { palette, metrics, typography, strokes } = ACTIVE;
  const pageW = doc.internal.pageSize.getWidth();
  const bandH = ptToUnit(doc, metrics.bandHeightPt);
  const marginU = ptToUnit(doc, metrics.marginPt);
  const eyebrowY = ptToUnit(doc, metrics.bandEyebrowYPt);
  const titleY = ptToUnit(doc, metrics.bandTitleYPt);
  const subtitleY = ptToUnit(doc, metrics.bandSubtitleYPt);

  setFill(doc, palette.bandBg);
  doc.rect(0, 0, pageW, bandH, "F");

  if (spec.eyebrow) {
    setText(doc, palette.gold);
    doc.setFont(typography.fontFamily, "normal");
    doc.setFontSize(typography.eyebrowSizePt);
    doc.text(spec.eyebrow.toUpperCase(), marginU, eyebrowY);
  }

  setText(doc, palette.gold);
  doc.setFont(typography.fontFamily, "bold");
  doc.setFontSize(typography.titleSizePt);
  doc.text(spec.title, marginU, titleY);

  if (spec.subtitle) {
    setText(doc, palette.subtitle);
    doc.setFont(typography.fontFamily, "normal");
    doc.setFontSize(typography.subtitleSizePt);
    doc.text(spec.subtitle, marginU, subtitleY);
  }

  // Thin gold hairline under the band.
  setDraw(doc, palette.gold);
  doc.setLineWidth(ptToUnit(doc, strokes.accentPt));
  doc.line(0, bandH, pageW, bandH);

  // Reset for downstream body drawing.
  setText(doc, palette.body);
  setDraw(doc, palette.rule);
  doc.setLineWidth(ptToUnit(doc, strokes.rulePt));

  return { nextY: bandH + ptToUnit(doc, metrics.bodyGapPt), bandBottom: bandH };
}

// ─── Footer ───────────────────────────────────────────────────────────────
export interface FooterOpts {
  pageNum: number;
  /** Left-side brand line. Defaults to the configured footerBrand. */
  brand?: string;
  /** Optional right-side text; when set the page number is inlined. */
  rightText?: string;
}

export function drawFooter(doc: jsPDF, opts: FooterOpts): void {
  const { palette, metrics, typography } = ACTIVE;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginU = ptToUnit(doc, metrics.marginPt);
  const yU = pageH - ptToUnit(doc, metrics.footerOffsetPt);
  setText(doc, palette.muted);
  doc.setFont(typography.fontFamily, "normal");
  doc.setFontSize(typography.footerSizePt);
  doc.text(opts.brand ?? ACTIVE.footerBrand, marginU, yU);
  const right = opts.rightText ?? `Page ${opts.pageNum}`;
  doc.text(right, pageW - marginU, yU, { align: "right" });
  setText(doc, palette.body);
}

// ─── Body helpers ─────────────────────────────────────────────────────────
/** Horizontal rule using the shared muted rule color. */
export function drawRule(doc: jsPDF, y: number, opts?: { color?: RGB; marginPt?: number }): void {
  const { palette, metrics, strokes } = ACTIVE;
  const pageW = doc.internal.pageSize.getWidth();
  const marginU = ptToUnit(doc, opts?.marginPt ?? metrics.marginPt);
  setDraw(doc, opts?.color ?? palette.rule);
  doc.setLineWidth(ptToUnit(doc, strokes.rulePt));
  doc.line(marginU, y, pageW - marginU, y);
}

/** Section heading — uppercase, small, gold underline. */
export function drawSectionHeading(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  opts?: { sizePt?: number; underline?: boolean },
): number {
  const { palette, typography, strokes } = ACTIVE;
  const sizePt = opts?.sizePt ?? typography.sectionHeadingSizePt;
  doc.setFont(typography.fontFamily, "bold");
  doc.setFontSize(sizePt);
  setText(doc, palette.body);
  doc.text(text.toUpperCase(), x, y);
  if (opts?.underline !== false) {
    const underY = y + ptToUnit(doc, sizePt * 0.3);
    setDraw(doc, palette.gold);
    doc.setLineWidth(ptToUnit(doc, strokes.accentPt));
    const width = doc.getTextWidth(text.toUpperCase());
    doc.line(x, underY, x + width, underY);
    setDraw(doc, palette.rule);
    doc.setLineWidth(ptToUnit(doc, strokes.rulePt));
  }
  return y + ptToUnit(doc, sizePt + 6);
}

// ─── Single export-doc factory ────────────────────────────────────────────
//
// Every PDF export in the app should go through `createExportDoc()` instead
// of calling `new jsPDF()` directly. This guarantees:
//
//   • one shared unit/format default (pt / letter),
//   • the Cinema Aurea cover band is painted uniformly (when `cover` is
//     supplied),
//   • an evidence footer is applied to every page in one pass via
//     `finalizeEvidenceFooters()` — no more hand-rolled `for (page...)`
//     loops that drift out of sync between exporters.
//
// The factory intentionally returns the raw `jsPDF` doc so callers keep
// full control of their body layout; only the chrome (cover + footer) is
// centralized.

export interface ExportDocEvidence {
  /** Full hash string; footer shows a 16-char prefix. */
  hash?: string | null;
  /** Bundle/schema label, e.g. "publication_evidence_bundle_v1". */
  label?: string | null;
  /** ISO timestamp or preformatted label shown next to `label`. */
  generatedAt?: string | null;
}

export interface CreateExportDocOpts {
  unit?: "pt" | "in" | "mm";
  format?: "letter" | "a4";
  /** When set, the shared title band is painted on page 1 immediately. */
  cover?: TitleBandSpec;
  /** Attached to every page footer during `finalizeEvidenceFooters()`. */
  evidence?: ExportDocEvidence;
  /** Overrides the default footer brand line (left side). */
  footerBrand?: string;
}

export interface ExportDoc {
  doc: jsPDF;
  /** Y position in doc units where body content should begin (post-cover). */
  readonly startY: number;
  /** Repaint the shared cover band on the current page; returns new startY. */
  paintCover(spec?: TitleBandSpec): number;
  /**
   * Loop every existing page and paint the shared evidence footer.
   * Call once at the very end, after all pages are drawn.
   */
  finalizeEvidenceFooters(opts?: { brand?: string; evidence?: ExportDocEvidence }): void;
}

function buildEvidenceRight(
  ev: ExportDocEvidence | undefined,
  page: number,
  total: number,
): string {
  const parts: string[] = [];
  if (ev?.hash) parts.push(ev.hash.slice(0, 16) + "…");
  parts.push(`Page ${page} of ${total}`);
  return parts.join(" · ");
}

function buildEvidenceBrand(
  ev: ExportDocEvidence | undefined,
  override: string | undefined,
): string {
  if (override) return override;
  const base = ACTIVE.footerBrand;
  if (!ev?.label) return base;
  const stamp = ev.generatedAt ? ` · ${ev.generatedAt}` : "";
  return `${ev.label}${stamp}`;
}

export function createExportDoc(opts: CreateExportDocOpts = {}): ExportDoc {
  const doc = new jsPDF({ unit: opts.unit ?? "pt", format: opts.format ?? "letter" });
  let startY = 0;

  const paintCover = (spec?: TitleBandSpec): number => {
    const s = spec ?? opts.cover;
    if (!s) return startY;
    const { nextY } = renderTitleBand(doc, s);
    startY = nextY;
    return nextY;
  };

  if (opts.cover) paintCover(opts.cover);

  const finalizeEvidenceFooters: ExportDoc["finalizeEvidenceFooters"] = (fopts) => {
    const ev = fopts?.evidence ?? opts.evidence;
    const brand = buildEvidenceBrand(ev, fopts?.brand ?? opts.footerBrand);
    const total = doc.getNumberOfPages();
    for (let p = 1; p <= total; p++) {
      doc.setPage(p);
      drawFooter(doc, {
        pageNum: p,
        brand,
        rightText: buildEvidenceRight(ev, p, total),
      });
    }
  };

  return {
    doc,
    get startY() {
      return startY;
    },
    paintCover,
    finalizeEvidenceFooters,
  } as ExportDoc;
}

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

function deepClone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function mergeDeep<T>(base: T, override: DeepPartial<T>): T {
  const out: any = Array.isArray(base) ? [...(base as any)] : { ...(base as any) };
  for (const key of Object.keys(override) as Array<keyof T>) {
    const ov = (override as any)[key];
    if (ov === undefined) continue;
    const bv = (base as any)[key];
    if (
      bv &&
      typeof bv === "object" &&
      !Array.isArray(bv) &&
      ov &&
      typeof ov === "object" &&
      !Array.isArray(ov)
    ) {
      out[key] = mergeDeep(bv, ov);
    } else {
      out[key] = ov;
    }
  }
  return out as T;
}
