import { retainedRecordMatchesProject } from './projectLibraryModel';
import { useEffect, useRef, useState } from 'react';
import { workspaceApi } from './api';
import { canonicalJson } from './canonical';
import { validateRecord } from './validation';
import { downloadLocalBlob } from './localDownload';
import { evaluateAssetOptionScenario } from '../../local/contracts/asset-valuation.mjs';
import { assetMarketPassport, marketChecklist, marketDetails, marketValidation, newMarketProfile, type MarketAsset, type MarketDetails, type MarketProject, type OptionInputs } from './assetMarketModel';
import AssetTokenPreparationPanel from './AssetTokenPreparationPanel';
import type { AssetMarketProfile, WorkspaceApi, WorkspaceRecord } from './types';
import './asset-market.css';

type Edit = { data: AssetMarketProfile; initial: string; version: number | null };
type Props = { project: MarketProject; asset?: MarketAsset; assets?: MarketAsset[]; parentHashes?: string[]; records: WorkspaceRecord[]; api?: Pick<WorkspaceApi, 'saveRecord'>; onSaved?(record: WorkspaceRecord): void; onDirty?(dirty: boolean): void; open?: boolean; disabled?: boolean };
const numericOptions: [keyof OptionInputs, string, string][] = [['underlyingReferenceValue', 'Underlying reference value', 'Currency units per described right'], ['strikePrice', 'Exercise price', 'Same currency and quantity'], ['timeToExpiryYears', 'Time to expiry (years)', 'e.g. 0.5 for six months'], ['annualRiskFreeRate', 'Annual interest rate', 'Decimal · 0.05 means 5%'], ['annualVolatility', 'Annual volatility', 'Decimal · 0.2 means 20%'], ['annualYield', 'Annual continuous yield', 'Decimal · enter 0 explicitly if none']];
const numberOrNull = (value: string) => value === '' ? null : Number(value);
export default function AssetMarketPanel({ project, asset, assets = [], parentHashes = [], records, api = workspaceApi, onSaved, onDirty, open = true, disabled = false }: Props) {
  const scope = `${project.id}:${project.sourceHash}`, scopeRef = useRef(scope), epoch = useRef(0);
  if (scopeRef.current !== scope) { scopeRef.current = scope; epoch.current++; }
  const key = `${scope}:${asset?.sha256 ?? ''}`, selected = useRef(key); selected.current = key;
  const [edits, setEdits] = useState<Record<string, Edit>>({}), [retained, setRetained] = useState<Record<string, WorkspaceRecord>>({});
  const [busy, setBusy] = useState(''), [feedback, setFeedback] = useState<{ key: string; error?: string; notice?: string }>(), [section, setSection] = useState<'identity' | 'rights' | 'edition' | 'value' | 'nft'>('identity');
  const [tokenDirty, setTokenDirty] = useState(false);
  const attempts = useRef<Record<string, { fingerprint: string; requestId: string }>>({}), alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  useEffect(() => { setBusy(''); }, [scope]);
  const id = asset ? `asset-market:${asset.sha256}` : '';
  const fromRecords = records.find(r => r.kind === 'asset-market-profile' && r.id === id && retainedRecordMatchesProject(r, project));
  const local = retained[key], saved = local && (!fromRecords || local.version > fromRecords.version) ? local : fromRecords;
  const edit = edits[key], profile = edit?.data ?? (saved?.data as AssetMarketProfile | undefined) ?? (asset ? newMarketProfile(project, asset, parentHashes) : undefined);
  const anyDirty = Object.entries(edits).some(([k, e]) => k.startsWith(`${scope}:`) && canonicalJson(e.data) !== e.initial);
  const dirty = Boolean(edit && canonicalJson(edit.data) !== edit.initial);
  useEffect(() => { onDirty?.(anyDirty || tokenDirty); }, [anyDirty, tokenDirty, onDirty]);
  const details = profile ? marketDetails(profile, true) : null, checklist = profile ? marketChecklist(profile, true) : [], invalid = profile ? marketValidation(profile, project) : null;
  const candidates = [...new Map(assets.filter(a => a.sha256 !== asset?.sha256).map(a => [a.sha256, a])).values()];
  const ownFeedback = feedback?.key === key ? feedback : null;
  function update(change: (profile: AssetMarketProfile) => AssetMarketProfile) {
    if (!profile || busy || disabled) return;
    const base = edit ?? { data: profile, initial: canonicalJson(profile), version: saved?.version ?? null };
    setEdits(old => ({ ...old, [key]: { ...base, data: change(base.data) } })); setFeedback(undefined);
  }
  function changeDetail(change: (value: MarketDetails) => MarketDetails) { update(value => ({ ...value, detailsJson: JSON.stringify(change(marketDetails(value, true))) })); }
  function changeOption(change: Partial<OptionInputs>) { changeDetail(d => ({ ...d, pricing: { ...d.pricing, optionScenario: { ...(d.pricing.optionScenario ?? {}), ...change } } })); }
  async function save() {
    if (!profile || busy || disabled || invalid) return;
    const capturedKey = key, capturedScope = scope, capturedEpoch = epoch.current, data = JSON.parse(canonicalJson(profile)) as AssetMarketProfile;
    const expectedVersion = edit ? edit.version : saved?.version ?? null, fingerprint = canonicalJson({ data, expectedVersion });
    if (attempts.current[key]?.fingerprint !== fingerprint) attempts.current[key] = { fingerprint, requestId: crypto.randomUUID() };
    setBusy(key); setFeedback(undefined);
    try {
      const record = await api.saveRecord({ id, kind: 'asset-market-profile', expectedVersion, requestId: attempts.current[key].requestId, data });
      await validateRecord(record);
      if (record.id !== id || record.kind !== 'asset-market-profile' || record.version !== (expectedVersion ?? 0) + 1 || canonicalJson(record.data) !== canonicalJson(data)) throw new Error('Saved profile did not match this exact draft.');
      if (!alive.current || scopeRef.current !== capturedScope || epoch.current !== capturedEpoch) return;
      setRetained(old => ({ ...old, [capturedKey]: record })); setEdits(old => { const next = { ...old }; delete next[capturedKey]; return next; }); onSaved?.(record);
      setFeedback({ key: capturedKey, notice: `Draft saved · version ${record.version}. No rights or tokens issued.` });
    } catch (error) {
      if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setFeedback({ key: capturedKey, error: `${error instanceof Error ? error.message : 'Save not confirmed.'} Edits are retained; retry uses the same request. For a conflict, compare with the latest saved profile before discarding.` });
    } finally { if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setBusy(''); }
  }
  async function exportPassport() {
    if (!profile || invalid || busy) return;
    const capturedKey = key, capturedScope = scope, capturedEpoch = epoch.current; setBusy(key);
    try { const passport = await assetMarketPassport(profile, project, saved); if (alive.current && selected.current === capturedKey && scopeRef.current === capturedScope && epoch.current === capturedEpoch) { downloadLocalBlob(new Blob([JSON.stringify(passport, null, 2)], { type: 'application/json' }), `asset-passport-${profile.assetHash.slice(0, 12)}-DRAFT.json`); setFeedback({ key, notice: 'Draft passport downloaded. Its checklist includes all open market requirements.' }); } }
    catch (error) { if (alive.current && selected.current === capturedKey && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setFeedback({ key, error: error instanceof Error ? error.message : 'Export failed.' }); }
    finally { if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setBusy(''); }
  }
  const option = evaluateAssetOptionScenario(details?.pricing.optionScenario);
  return <section className="asset-market" aria-label="Asset market preparation" hidden={!open || !asset} data-unsaved={anyDirty || tokenDirty ? 'true' : 'false'}>{asset && profile && details && <>
    <header><span className="eyebrow">ASSET PASSPORT · DRAFT</span><h3>Prepare its next life.</h3><p>Describe what a buyer could receive, retain the supporting documents and propose an edition.</p></header>
    <div className="asset-market-progress"><strong>{checklist.filter(row => row.complete).length}/{checklist.length}</strong><span>preparation items filled<br/><small>Rights review and market connection still required</small></span></div>
    <nav aria-label="Asset passport sections">{(['identity', 'rights', 'edition', 'value', 'nft'] as const).map(name => <button key={name} aria-pressed={section === name} onClick={() => setSection(name)}>{({ identity: 'Identity', rights: 'Licence', edition: 'Edition', value: 'Value', nft: 'NFT & blockchain' })[name]}</button>)}</nav>
    <fieldset disabled={Boolean(busy) || disabled}>
      <div hidden={section !== 'identity'}><label>Asset title<input maxLength={240} value={profile.title} onChange={e => update(d => ({ ...d, title: e.target.value }))}/></label><label>Description<textarea rows={3} maxLength={16000} value={details.description} onChange={e => changeDetail(d => ({ ...d, description: e.target.value }))}/></label>{([['creator', 'Creator'], ['issuer', 'Proposed issuer'], ['copyrightHolder', 'Declared copyright holder'], ['credits', 'Credits']] as const).map(([name, label]) => <label key={name}>{label}<input maxLength={16000} value={details[name]} onChange={e => changeDetail(d => ({ ...d, [name]: e.target.value }))}/></label>)}<details><summary>Exact original</summary><code>{asset.sha256}</code><p>{asset.mimeType}</p></details></div>
      <div hidden={section !== 'rights'}><label>Rights offered<textarea rows={3} maxLength={16000} placeholder="Personal display, commercial reproduction, exclusive licence…" value={details.rightsScope} onChange={e => changeDetail(d => ({ ...d, rightsScope: e.target.value }))}/></label><div className="asset-market-pair">{([['territory', 'Territory'], ['term', 'Term / expiry']] as const).map(([name, label]) => <label key={name}>{label}<input maxLength={16000} value={details[name]} onChange={e => changeDetail(d => ({ ...d, [name]: e.target.value }))}/></label>)}</div>{([['transferable', 'Can the declared licence be transferred?'], ['derivativesAllowed', 'Does it permit derivative works?']] as const).map(([name, label]) => <label key={name}>{label}<select value={details[name] === null ? '' : String(details[name])} onChange={e => changeDetail(d => ({ ...d, [name]: e.target.value === '' ? null : e.target.value === 'true' }))}><option value="">Not reviewed</option><option value="true">Declared yes · evidence required</option><option value="false">Declared no</option></select></label>)}{details.transferable === false && <p className="asset-market-warning">This draft says transfer is prohibited. Do not offer a transferable edition.</p>}
      {(['licenceEvidenceHashes', 'parentAssetHashes'] as const).map(field => <div className="asset-market-evidence" key={field}><label>{field === 'licenceEvidenceHashes' ? 'Attach a retained licence document' : 'Link a source asset'}<select value="" onChange={e => { if (e.target.value) changeDetail(d => ({ ...d, [field]: [...new Set([...d[field], e.target.value])] })); }}><option value="">Choose an original from this project…</option>{candidates.filter(a => !details[field].includes(a.sha256)).map(a => <option value={a.sha256} key={a.sha256}>{a.title} · {a.sha256.slice(0, 8)}</option>)}</select></label>{details[field].map(hash => <div key={hash}><span>{candidates.find(a => a.sha256 === hash)?.title ?? hash.slice(0, 16)}<small>{hash.slice(0, 16)}</small></span><button aria-label={`Remove ${field === 'licenceEvidenceHashes' ? 'licence document' : 'source asset'} ${hash.slice(0, 8)}`} onClick={() => changeDetail(d => ({ ...d, [field]: d[field].filter(x => x !== hash) }))}>Remove</button></div>)}</div>)}<p className="asset-market-note">An attached file is evidence to review. NFT ownership and copyright or licence rights are distinct. Source obligations must also be cleared for a comic or other derivative.</p></div>
      <div hidden={section !== 'edition'}><label>Edition series identity<input maxLength={240} placeholder="A stable ID for this proposed series" value={details.edition.seriesId} onChange={e => changeDetail(d => ({ ...d, edition: { ...d.edition, seriesId: e.target.value } }))}/></label><div className="asset-market-pair"><label>Proposed lifetime cap<input type="number" min={1} max={1000000} step={1} value={details.edition.cap ?? ''} onChange={e => changeDetail(d => ({ ...d, edition: { ...d.edition, cap: numberOrNull(e.target.value) } }))}/></label><label>Proposed standard<select value={details.edition.tokenStandard} onChange={e => changeDetail(d => ({ ...d, edition: { ...d.edition, tokenStandard: e.target.value as MarketDetails['edition']['tokenStandard'] } }))}><option value="UNDECIDED">Not selected</option><option value="ERC721">ERC-721 · individually identified</option><option value="ERC1155">ERC-1155 · edition quantities</option></select></label></div><label>Requested royalty (basis points)<input type="number" min={0} max={10000} step={1} value={details.edition.royaltyBps ?? ''} onChange={e => changeDetail(d => ({ ...d, edition: { ...d.edition, royaltyBps: numberOrNull(e.target.value) } }))}/><small>100 basis points = 1%. Collection is not guaranteed.</small></label><p className="asset-market-note">No tokens have been issued by this draft. A proposed cap does not reserve supply or certify worldwide uniqueness. Contract and supply enforcement belong to the later market integration.</p></div>
      <div hidden={section !== 'value'}><label>Price currency<select value={details.pricing.currency} onChange={e => changeDetail(d => ({ ...d, pricing: { ...d.pricing, currency: e.target.value } }))}><option value="">Choose currency</option>{['USD', 'CAD', 'EUR', 'GBP'].map(c => <option key={c}>{c}</option>)}</select></label><div className="asset-market-pair">{([['askingMinor', 'Asking price'], ['creationCostMinor', 'Recorded creation cost']] as const).map(([name, label]) => <label key={name}>{label} (minor units)<input aria-label={`${label} (minor units)`} type="number" min={0} step={1} value={details.pricing[name] ?? ''} onChange={e => changeDetail(d => ({ ...d, pricing: { ...d.pricing, [name]: numberOrNull(e.target.value) } }))}/><small>100 = 1 {details.pricing.currency || 'currency unit'}. Blank = unknown.</small></label>)}</div><p className="asset-market-note">These are declared amounts. An asking price is not a sale, and an edition cap does not multiply the project’s market value.</p>
      <details className="asset-market-option"><summary>Black–Scholes option scenario</summary><p>Explore the theoretical premium for an explicitly described European option. This model does not appraise the NFT.</p><label>Right / underlying being modeled<textarea rows={2} value={details.pricing.optionScenario?.underlyingDescription ?? ''} onChange={e => changeOption({ underlyingDescription: e.target.value })}/></label><div className="asset-market-pair"><label>Option type<select value={details.pricing.optionScenario?.optionType ?? ''} onChange={e => changeOption({ optionType: e.target.value })}><option value="">Choose</option><option value="CALL">Call · right to buy</option><option value="PUT">Put · right to sell</option></select></label><label>Scenario currency<select value={details.pricing.optionScenario?.currency ?? ''} onChange={e => changeOption({ currency: e.target.value })}><option value="">Choose</option>{['USD', 'CAD', 'EUR', 'GBP'].map(c => <option key={c}>{c}</option>)}</select></label></div>{numericOptions.map(([name, label, hint]) => <label key={name}>{label}<input aria-label={label} type="number" step="any" value={details.pricing.optionScenario?.[name] ?? ''} onChange={e => changeOption({ [name]: numberOrNull(e.target.value) })}/><small>{hint}</small></label>)}<output aria-label="Hypothetical option result">{option.status === 'CALCULATED' ? `${option.theoreticalValue.toFixed(6)} ${details.pricing.optionScenario?.currency} · hypothetical option premium` : option.status === 'INVALID_INPUT' ? 'Invalid scenario inputs' : 'Insufficient data · enter every scenario input'}</output><details><summary>Model assumptions</summary><ul>{option.assumptions.map((text: string) => <li key={text}>{text}</li>)}</ul></details><a href="https://www.optionseducation.org/advancedconcepts/black-scholes-formula" target="_blank" rel="noreferrer">Formula and assumptions · Options Industry Council</a></details></div>
    </fieldset>
    <div hidden={section !== 'nft'}><AssetTokenPreparationPanel project={project} assetHash={asset.sha256} records={saved ? [...records.filter(record => record.id !== saved.id), saved] : records} onSaved={onSaved} onDirty={setTokenDirty} passportDirty={dirty} disabled={disabled || Boolean(busy)}/></div>
    <details className="asset-market-checks"><summary>Preparation checklist</summary><ul>{checklist.map(row => <li key={row.id} data-complete={row.complete}><span aria-hidden="true">{row.complete ? '✓' : '○'}</span> {row.label}</li>)}</ul><p>Filled fields prepare a review packet. Rights, parent licences, edition issuance and settlement still need verification.</p></details>
    {invalid && <p role="alert">{invalid}</p>}{ownFeedback?.error && <p role="alert">{ownFeedback.error}</p>}{ownFeedback?.notice && <p role="status">{ownFeedback.notice}</p>}
    <footer><button className="primary" disabled={disabled || Boolean(busy) || Boolean(invalid) || (!dirty && Boolean(saved))} onClick={() => void save()}>{busy === key ? 'Working…' : 'Save asset passport'}</button><button disabled={Boolean(busy) || Boolean(invalid)} onClick={() => void exportPassport()}>Export draft packet</button>{dirty && <button disabled={Boolean(busy)} onClick={() => { if (window.confirm('Discard this asset’s unsaved passport edits and return to the latest loaded version?')) { setEdits(old => { const next = { ...old }; delete next[key]; return next; }); setFeedback(undefined); } }}>Discard edits</button>}</footer><small>{dirty ? 'Unsaved passport edits' : saved ? `Saved draft · v${saved.version}` : 'No saved passport yet'}</small>
  </>}</section>;
}
