import { useEffect, useRef, useState } from 'react';
import { calculateParticipationPool, defaultParticipation, validateParticipation, type ParticipationContribution, type ParticipationPool, type ParticipationRight, type ParticipationSubject, type ProjectParticipation } from '../../local/contracts/project-participation.mjs';
import type { BudgetLine, ProductionBudget } from '../../local/contracts/production-budget.mjs';
import { workspaceApi } from './api';
import { canonicalJson, hashCanonical } from './canonical';
import { downloadLocalBlob } from './localDownload';
import { retainedRecordMatchesProject } from './projectLibraryModel';
import { validateRecord } from './validation';
import type { WorkspaceApi, WorkspaceProject, WorkspaceRecord } from './types';
import './project-participation.css';

type Asset = { sha256: string; title: string; mimeType: string };
type Props = { project: WorkspaceProject; records: WorkspaceRecord[]; assets: Asset[]; open: boolean; onSaved?(record: WorkspaceRecord): void; onDirty?(dirty: boolean): void; onOpenBudget?(targetId?: string): void; api?: Pick<WorkspaceApi, 'saveRecord'> };
type Edit = { data: ProjectParticipation; initial: string; version: number | null; numbers: Record<string, string> };
type Section = 'contributors' | 'rights' | 'points';
const poolNames = { RECEIPTS: 'Receipts participation', DEFINED_PROCEEDS: 'Defined proceeds', COPYRIGHT_INTEREST: 'Copyright interest', COMPANY_EQUITY: 'Company equity' };
const rightNames = { COPYRIGHT: 'Copyright claim', LICENCE: 'Licence', PERFORMANCE: 'Performance permission', VOICE_LIKENESS: 'Voice & likeness', DIGITAL_REPLICA: 'Digital replica', OTHER: 'Other right or consent' };
const subjectKinds = new Set(['screenplay-draft', 'casting-draft', 'concept-draft', 'story-plan-draft', 'pitch-draft', 'writing-note', 'universe-entity', 'universe-profile', 'universe-claim', 'universe-link', 'universe-artwork', 'universe-agent', 'universe-rehearsal', 'universe-continuity-plan', 'universe-production-plan']);
const recordTitle = (record: WorkspaceRecord) => { const value = record.data as Record<string, unknown>; return String(value.title || value.name || value.performer || value.characterId || value.entityId || record.id); };
const projectSubject = (project: WorkspaceProject): ParticipationSubject => ({ kind: 'PROJECT', label: project.title, assetHash: null, recordRef: null });
const numberText = (value: number | null) => value === null ? '' : `${Math.floor(value / 100)}${value % 100 ? `.${String(value % 100).padStart(2, '0').replace(/0$/, '')}` : ''}`;
/** Parse exactly two decimal places, without rounding user input. */
function decimalInput(text: string): { value: number | null; error: string } {
  if (!text.trim()) return { value: null, error: '' };
  if (!/^\d+(?:\.\d{0,2})?$/.test(text)) return { value: null, error: 'Use a nonnegative amount with no more than two decimal places.' };
  const [whole, fraction = ''] = text.split('.'), value = BigInt(whole) * 100n + BigInt(fraction.padEnd(2, '0'));
  return value > BigInt(Number.MAX_SAFE_INTEGER) ? { value: null, error: 'This amount is too large to calculate exactly.' } : { value: Number(value), error: '' };
}
const money = (value: number | null, currency: string) => value === null ? 'Unknown' : `${currency || 'Currency unspecified'} ${new Intl.NumberFormat('en-US').format(BigInt(value) / 100n)}.${String(BigInt(value) % 100n).padStart(2, '0')}`;
const subjectKey = (subject: ParticipationSubject) => subject.kind === 'PROJECT' ? 'PROJECT' : subject.kind === 'ASSET' ? `ASSET:${subject.assetHash}` : `RECORD:${subject.recordRef?.id}:${subject.recordRef?.version}:${subject.recordRef?.sha256}`;
function subjectIssue(subject: ParticipationSubject, records: WorkspaceRecord[], assets: Asset[]) {
  if (subject.kind === 'ASSET' && !assets.some(asset => asset.sha256 === subject.assetHash)) return 'This asset is no longer in the retained project files. Review its subject.';
  if (subject.kind !== 'RECORD') return '';
  const current = records.find(record => record.id === subject.recordRef?.id);
  return !current ? 'This saved subject is unavailable. Choose a retained subject before saving.' : current.version !== subject.recordRef?.version || current.sha256 !== subject.recordRef?.sha256 ? 'This subject has a newer saved version. Review it and select the current version before saving.' : '';
}
function SubjectField({ value, onChange, project, records, assets }: { value: ParticipationSubject; onChange(value: ParticipationSubject): void; project: WorkspaceProject; records: WorkspaceRecord[]; assets: Asset[] }) {
  const options: { key: string; label: string; value: ParticipationSubject }[] = [{ key: 'PROJECT', label: `Whole project · ${project.title}`, value: projectSubject(project) }, ...assets.map(asset => ({ key: `ASSET:${asset.sha256}`, label: `File · ${asset.title}`, value: { kind: 'ASSET' as const, label: asset.title, assetHash: asset.sha256, recordRef: null } })), ...records.map(record => ({ key: `RECORD:${record.id}:${record.version}:${record.sha256}`, label: `${record.kind.replace(/-/g, ' ')} · ${recordTitle(record)} · v${record.version}`, value: { kind: 'RECORD' as const, label: recordTitle(record), assetHash: null, recordRef: { id: record.id, version: record.version, sha256: record.sha256 } } }))];
  const key = subjectKey(value), issue = subjectIssue(value, records, assets);
  return <div className="participation-subject"><label>Subject<select value={key} onChange={event => { const choice = options.find(option => option.key === event.target.value); if (choice) onChange(choice.value); }}>{!options.some(option => option.key === key) && <option value={key}>{value.label || 'Saved subject'} · review needed</option>}{options.map(option => <option key={option.key} value={option.key}>{option.label}</option>)}</select></label>{value.recordRef && <small>Exact version {value.recordRef.version} · {value.recordRef.sha256.slice(0, 12)}</small>}{issue && <p className="participation-warning">{issue}</p>}</div>;
}
function EvidenceField({ hashes, assets, onChange }: { hashes: string[]; assets: Asset[]; onChange(hashes: string[]): void }) {
  return <div className="participation-evidence"><label>Supporting document or file<select value="" onChange={event => { if (event.target.value) onChange([...hashes, event.target.value]); }}><option value="">Attach a retained project file…</option>{assets.filter(asset => !hashes.includes(asset.sha256)).map(asset => <option key={asset.sha256} value={asset.sha256}>{asset.title} · {asset.sha256.slice(0, 8)}</option>)}</select></label>{hashes.map(hash => <div className="participation-link" key={hash}><span>{assets.find(asset => asset.sha256 === hash)?.title || `Unavailable file · ${hash.slice(0, 12)}`}<small>{hash.slice(0, 12)}</small></span><button type="button" onClick={() => onChange(hashes.filter(value => value !== hash))} aria-label={`Remove supporting file ${hash.slice(0, 8)}`}>Remove</button></div>)}</div>;
}
function NumberField({ label, value, onChange, hint, percent = false }: { label: string; value: string; onChange(value: string): void; hint?: string; percent?: boolean }) {
  const parsed = decimalInput(value), error = parsed.error || (percent && parsed.value !== null && parsed.value > 10000 ? 'A share cannot exceed 100% of this pool.' : '');
  return <label>{label}<input aria-label={label} inputMode="decimal" value={value} onChange={event => onChange(event.target.value)} aria-invalid={Boolean(error)} placeholder="Unknown"/>{hint && <small>{hint}</small>}{error && <span className="participation-warning">{error}</span>}</label>;
}

export default function ProjectParticipationPanel({ project, records, assets, open, onSaved, onDirty, onOpenBudget, api = workspaceApi }: Props) {
  const scope = `${project.id}:${project.sourceHash}`, scopeRef = useRef(scope), epoch = useRef(0);
  if (scopeRef.current !== scope) { scopeRef.current = scope; epoch.current++; }
  const alive = useRef(true), attempts = useRef<Record<string, { fingerprint: string; requestId: string }>>({});
  const [edits, setEdits] = useState<Record<string, Edit>>({}), [retained, setRetained] = useState<Record<string, WorkspaceRecord>>({});
  const [section, setSection] = useState<Section>('contributors'), [partySelection, setPartySelection] = useState(''), [poolSelection, setPoolSelection] = useState('');
  const [busy, setBusy] = useState(''), [feedback, setFeedback] = useState<{ scope: string; error?: string; notice?: string }>();
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const id = `participation:${project.id}`;
  const latestRecords = [...records.reduce((latest, record) => { if (!latest.has(record.id) || latest.get(record.id)!.version < record.version) latest.set(record.id, record); return latest; }, new Map<string, WorkspaceRecord>()).values()];
  const fromRecords = latestRecords.find(record => record.id === id && record.kind === 'project-participation' && retainedRecordMatchesProject(record, project));
  const locallySaved = retained[scope], saved = locallySaved && (!fromRecords || locallySaved.version > fromRecords.version) ? locallySaved : fromRecords;
  const edit = edits[scope], data = edit?.data ?? (saved?.data as ProjectParticipation | undefined) ?? defaultParticipation({ ...project });
  const scopedRecords = latestRecords.filter(record => retainedRecordMatchesProject(record, project));
  const subjects = scopedRecords.filter(record => subjectKinds.has(record.kind));
  const retainedAssets = [...new Map(assets.map(asset => [asset.sha256, asset])).values()];
  const budgetRecord = scopedRecords.find(record => record.kind === 'production-budget' && record.id === `production-budget:${project.id}`);
  const budgetLines: BudgetLine[] = budgetRecord ? (budgetRecord.data as ProductionBudget).lines : [];
  const party = data.parties.find(value => value.id === partySelection) ?? data.parties[0];
  const pool = data.pools.find(value => value.id === poolSelection) ?? data.pools[0];
  const activeNumbers = new Set(data.pools.flatMap(value => [`${value.id}:receiptsMinor`, `${value.id}:deductionsMinor`, `${value.id}:recoupmentMinor`, ...value.allocations.map(allocation => `${value.id}:${allocation.id}`)]));
  const invalidNumber = Object.entries(edit?.numbers ?? {}).find(([key, value]) => activeNumbers.has(key) && decimalInput(value).error);
  const dirty = Boolean(edit && (canonicalJson(edit.data) !== edit.initial || invalidNumber));
  useEffect(() => { onDirty?.(dirty || busy === scope); }, [dirty, busy, scope, onDirty]);
  const working = busy === scope, ownFeedback = feedback?.scope === scope ? feedback : undefined;
  let invalid = '';
  try { validateParticipation(data, { ...project }); } catch (error) { invalid = error instanceof Error ? error.message : 'Review the draft fields before saving.'; }
  if (invalidNumber) invalid = 'A scenario amount or percentage has more than two decimal places or is invalid. Correct the highlighted input before saving.';
  const references = [...data.contributions, ...data.rights, ...data.pools];
  const staleSubjects = references.filter(value => subjectIssue(value.subject, subjects, retainedAssets));
  const missingEvidence = [...data.contributions, ...data.rights, ...data.pools.flatMap(value => value.allocations)].some(value => value.evidenceHashes.some(hash => !retainedAssets.some(asset => asset.sha256 === hash)));
  const missingBudget = data.contributions.some(value => value.budgetLineIds.some(lineId => !budgetLines.some(line => line.id === lineId)));
  const referenceError = staleSubjects.length ? `${staleSubjects.length} subject link${staleSubjects.length === 1 ? '' : 's'} need review before saving. Reselect the current saved version in the affected entry.` : missingEvidence ? 'A supporting file is no longer retained in this project. Review its evidence links before saving.' : missingBudget ? 'A linked cost line is no longer in the saved budget. Review the contribution’s budget links before saving.' : '';
  const disputed = data.rights.filter(value => value.status === 'DISPUTED').length + data.pools.flatMap(value => value.allocations).filter(value => value.agreementStatus === 'DISPUTED').length;
  const partyName = (partyId: string) => data.parties.find(value => value.id === partyId)?.name || 'Unnamed contributor';
  function update(change: (current: ProjectParticipation) => ProjectParticipation, number?: { key: string; value: string }) {
    if (working) return;
    const base = edit ?? { data, initial: canonicalJson(data), version: saved?.version ?? null, numbers: {} };
    setEdits(previous => ({ ...previous, [scope]: { ...base, data: change(base.data), numbers: number ? { ...base.numbers, [number.key]: number.value } : base.numbers } })); setFeedback(undefined);
  }
  function changeContribution(contributionId: string, change: Partial<ParticipationContribution>) { update(current => ({ ...current, contributions: current.contributions.map(value => value.id === contributionId ? { ...value, ...change } : value) })); }
  function changeRight(rightId: string, change: Partial<ParticipationRight>) { update(current => ({ ...current, rights: current.rights.map(value => value.id === rightId ? { ...value, ...change } : value) })); }
  function changePool(change: Partial<ParticipationPool>) { if (pool) update(current => ({ ...current, pools: current.pools.map(value => value.id === pool.id ? { ...value, ...change } : value) })); }
  function changeNumber(key: string, text: string, change: (current: ProjectParticipation, value: number | null) => ProjectParticipation) {
    const result = decimalInput(text); update(current => result.error ? current : change(current, result.value), { key, value: text });
  }
  function addParty() { const newId = crypto.randomUUID(); update(current => ({ ...current, parties: [...current.parties, { id: newId, name: '', kind: 'PERSON' }] })); setPartySelection(newId); }
  function addContribution() { if (party) update(current => ({ ...current, contributions: [...current.contributions, { id: crypto.randomUUID(), partyId: party.id, role: '', subject: projectSubject(project), description: '', credit: '', evidenceHashes: [], budgetLineIds: [] }] })); }
  function addRight() { if (party) update(current => ({ ...current, rights: [...current.rights, { id: crypto.randomUUID(), partyId: party.id, rightType: 'COPYRIGHT', subject: projectSubject(project), scope: '', territory: '', term: '', jurisdiction: '', status: 'CLAIMED', evidenceHashes: [] }] })); }
  function addPool() { const newId = crypto.randomUUID(); update(current => ({ ...current, pools: [...current.pools, { id: newId, name: '', kind: 'RECEIPTS', subject: projectSubject(project), definition: '', entityName: '', currency: '', receiptsMinor: null, deductionsMinor: null, recoupmentMinor: null, allocations: [] }] })); setPoolSelection(newId); }
  function changePoolKind(kind: ParticipationPool['kind']) {
    if (!pool || kind === pool.kind) return;
    if ([pool.receiptsMinor, pool.deductionsMinor, pool.recoupmentMinor].some(value => value !== null) && !window.confirm('Changing this pool type clears its scenario amounts. Continue?')) return;
    changePool({ kind, currency: kind === 'COPYRIGHT_INTEREST' || kind === 'COMPANY_EQUITY' ? '' : pool.currency, receiptsMinor: null, deductionsMinor: null, recoupmentMinor: null });
    setEdits(previous => { const current = previous[scope]; if (!current) return previous; const numbers = { ...current.numbers }; for (const field of ['receiptsMinor', 'deductionsMinor', 'recoupmentMinor']) delete numbers[`${pool.id}:${field}`]; return { ...previous, [scope]: { ...current, numbers } }; });
  }
  async function save() {
    if (working || invalid || referenceError) return;
    const capturedScope = scope, capturedEpoch = epoch.current, draft = JSON.parse(canonicalJson(data)) as ProjectParticipation;
    const expectedVersion = edit ? edit.version : saved?.version ?? null, fingerprint = canonicalJson({ data: draft, expectedVersion });
    if (attempts.current[scope]?.fingerprint !== fingerprint) attempts.current[scope] = { fingerprint, requestId: crypto.randomUUID() };
    setBusy(scope); setFeedback(undefined);
    try {
      const record = await api.saveRecord({ id, kind: 'project-participation', expectedVersion, requestId: attempts.current[scope].requestId, data: draft }, project);
      await validateRecord(record, project);
      if (record.id !== id || record.kind !== 'project-participation' || record.version !== (expectedVersion ?? 0) + 1 || canonicalJson(record.data) !== canonicalJson(draft)) throw new Error('The saved participation record did not match this exact draft.');
      if (!alive.current || scopeRef.current !== capturedScope || epoch.current !== capturedEpoch) return;
      setRetained(previous => ({ ...previous, [capturedScope]: record })); setEdits(previous => { const next = { ...previous }; delete next[capturedScope]; return next; });
      onSaved?.(record); setFeedback({ scope: capturedScope, notice: `Participation draft saved · version ${record.version}.` });
    } catch (error) {
      if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setFeedback({ scope: capturedScope, error: `${error instanceof Error ? error.message : 'Save was not confirmed.'} Your edits are retained. Retry uses the same request; for a version conflict, export your draft before comparing the latest saved version.` });
    } finally { if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setBusy(''); }
  }
  async function exportDraft() {
    if (working || invalid) return;
    const capturedScope = scope, capturedEpoch = epoch.current, draft = JSON.parse(canonicalJson(data)) as ProjectParticipation; setBusy(scope);
    try {
      const hash = await hashCanonical(draft);
      const packet = { schema: 'qimovi-participation-review/v1', status: 'DRAFT_FOR_REVIEW', project: { id: project.id, title: project.title, sourceHash: draft.sourceHash }, draft, draftSha256: hash, savedRecord: saved && saved.sha256 === hash ? { id: saved.id, version: saved.version, sha256: saved.sha256 } : null, scenarios: draft.pools.map(value => ({ poolId: value.id, name: value.name, definition: value.definition, currency: value.currency, result: calculateParticipationPool(value) })), budgetReferences: budgetRecord ? { record: { id: budgetRecord.id, version: budgetRecord.version, sha256: budgetRecord.sha256 }, contributions: draft.contributions.map(value => ({ contributionId: value.id, lineIds: value.budgetLineIds })) } : null, reviewWarnings: [referenceError, disputed ? `${disputed} disputed entry or entries require review.` : ''].filter(Boolean), declaration: 'Authored claims, proposed allocations and hypothetical scenarios only. Attached documents are recorded, not legally verified. This packet grants no rights, issues no equity, and records no payable amount, payment or accounting settlement. Each percentage applies only to its named pool; budget fees, residuals and separate obligations remain separate.' };
      if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) { downloadLocalBlob(new Blob([JSON.stringify(packet, null, 2)], { type: 'application/json' }), `participation-${project.id.replace(/[^a-zA-Z0-9_-]/g, '_')}-DRAFT.json`); setFeedback({ scope, notice: 'Draft review packet exported with scenarios and budget references.' }); }
    } catch (error) { if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setFeedback({ scope, error: error instanceof Error ? error.message : 'Export failed.' }); }
    finally { if (alive.current && scopeRef.current === capturedScope && epoch.current === capturedEpoch) setBusy(''); }
  }
  const subjectProps = { project, records: subjects, assets: retainedAssets };
  const partyIsUsed = party && (data.contributions.some(value => value.partyId === party.id) || data.rights.some(value => value.partyId === party.id) || data.pools.some(value => value.allocations.some(allocation => allocation.partyId === party.id)));
  const calculation = pool ? calculateParticipationPool(pool) : null;
  return <section className="project-participation" aria-label="Project participation" hidden={!open} aria-busy={working} data-unsaved={dirty ? 'true' : 'false'}>
    <header className="participation-heading"><div><span className="participation-eyebrow">PROJECT BUSINESS · DRAFT</span><h2>People, rights & points</h2><p>Record who contributed, the rights being claimed and the terms you want to review.</p></div><span className="participation-draft-state">{dirty ? 'Unsaved changes' : saved ? `Saved draft · v${saved.version}` : 'No saved draft'}</span></header>
    <nav className="participation-tabs" aria-label="Participation sections">{([['contributors', 'Contributors'], ['rights', 'Rights & consent'], ['points', 'Points & scenarios']] as const).map(([key, label]) => <button type="button" key={key} aria-pressed={section === key} onClick={() => setSection(key)}>{label}</button>)}</nav>
    {disputed > 0 && <p className="participation-warning participation-dispute">{disputed} disputed {disputed === 1 ? 'entry' : 'entries'} · Review the affected claims or allocations. Any figures remain hypothetical.</p>}
    <fieldset className="participation-workspace" disabled={working}>
      {section !== 'points' ? <div className="participation-layout">
        <aside className="participation-index" aria-label="Contributors"><div className="participation-section-title"><h3>Contributors</h3><span>{data.parties.length}</span></div>{data.parties.map(value => <button type="button" className="participation-index-item" key={value.id} aria-pressed={party?.id === value.id} onClick={() => setPartySelection(value.id)}><strong>{value.name || 'Unnamed contributor'}</strong><small>{value.kind === 'PERSON' ? 'Person' : 'Organization'}</small></button>)}<button type="button" className="participation-add" onClick={addParty}>+ Add contributor</button><p className="participation-aside-note">Roles describe the work. Ownership, consent and compensation each need their own terms.</p></aside>
        <div className="participation-editor">{!party ? <div className="participation-empty"><span>01</span><h3>Start with the people.</h3><p>Add a character creator, co-writer, performer or organization. Names and shares start blank.</p><button type="button" onClick={addParty}>Add first contributor</button></div> : <>
          <div className="participation-section-title"><h3>{section === 'contributors' ? 'Contribution & credit' : `Rights for ${party.name || 'this contributor'}`}</h3></div>
          {section === 'contributors' ? <><div className="participation-pair"><label>Name<input maxLength={240} value={party.name} onChange={event => update(current => ({ ...current, parties: current.parties.map(value => value.id === party.id ? { ...value, name: event.target.value } : value) }))}/></label><label>Contributor type<select value={party.kind} onChange={event => update(current => ({ ...current, parties: current.parties.map(value => value.id === party.id ? { ...value, kind: event.target.value as 'PERSON' | 'ORGANIZATION' } : value) }))}><option value="PERSON">Person</option><option value="ORGANIZATION">Organization</option></select></label></div>
            {data.contributions.filter(value => value.partyId === party.id).map((value, index) => <article className="participation-entry" key={value.id} aria-label={`Contribution ${index + 1}`}><div className="participation-section-title"><h4>Contribution {index + 1}</h4><button type="button" className="participation-remove" onClick={() => update(current => ({ ...current, contributions: current.contributions.filter(row => row.id !== value.id) }))}>Remove contribution</button></div><label>Role<input value={value.role} maxLength={240} placeholder="Character creator, co-writer, actor…" onChange={event => changeContribution(value.id, { role: event.target.value })}/></label><SubjectField {...subjectProps} value={value.subject} onChange={subject => changeContribution(value.id, { subject })}/><label>Work contributed<textarea rows={3} maxLength={8000} value={value.description} onChange={event => changeContribution(value.id, { description: event.target.value })}/></label><label>Proposed credit wording<input maxLength={2000} value={value.credit} placeholder="Exact wording and placement to review" onChange={event => changeContribution(value.id, { credit: event.target.value })}/></label><EvidenceField assets={retainedAssets} hashes={value.evidenceHashes} onChange={evidenceHashes => changeContribution(value.id, { evidenceHashes })}/><div className="participation-budget-links"><label>Link a saved budget line<select value="" onChange={event => { if (event.target.value) changeContribution(value.id, { budgetLineIds: [...value.budgetLineIds, event.target.value] }); }}><option value="">{budgetLines.length ? 'Choose a cost line…' : 'Save a production budget to link costs'}</option>{budgetLines.filter(line => !value.budgetLineIds.includes(line.id)).map(line => <option key={line.id} value={line.id}>{line.label || line.id} · {line.currency}</option>)}</select></label>{value.budgetLineIds.map(lineId => { const line = budgetLines.find(row => row.id === lineId); return <div className="participation-link" key={lineId}><span>{line?.label || `Unavailable cost line · ${lineId}`}</span>{line && onOpenBudget && <button type="button" onClick={() => onOpenBudget(line.targetId)}>Open cost</button>}<button type="button" onClick={() => changeContribution(value.id, { budgetLineIds: value.budgetLineIds.filter(row => row !== lineId) })}>Unlink</button></div>; })}<small>Fees stay in the production budget. Linking costs does not deduct them from a participation pool.</small>{onOpenBudget && <button type="button" className="participation-text-button" onClick={() => onOpenBudget()}>Open production budget</button>}</div></article>)}
            <button type="button" className="participation-add" onClick={addContribution}>+ Add contribution</button><div className="participation-delete-person"><button type="button" className="participation-remove" disabled={Boolean(partyIsUsed)} onClick={() => update(current => ({ ...current, parties: current.parties.filter(value => value.id !== party.id) }))}>Remove contributor</button>{partyIsUsed && <small>Remove this contributor’s contributions, rights and allocations first.</small>}</div></> : <>
            <p className="participation-section-note">Describe each right and permission separately. A performer credit does not establish character ownership or digital replica consent.</p>
            {data.rights.filter(value => value.partyId === party.id).map((value, index) => <article className="participation-entry" key={value.id} aria-label={`Right ${index + 1}`}><div className="participation-section-title"><h4>Right or permission {index + 1}</h4><button type="button" className="participation-remove" onClick={() => update(current => ({ ...current, rights: current.rights.filter(row => row.id !== value.id) }))}>Remove right</button></div><div className="participation-pair"><label>Right type<select value={value.rightType} onChange={event => changeRight(value.id, { rightType: event.target.value as ParticipationRight['rightType'] })}>{Object.entries(rightNames).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>Review status<select value={value.status} onChange={event => changeRight(value.id, { status: event.target.value as ParticipationRight['status'] })}><option value="CLAIMED">Claimed · review needed</option><option value="DOCUMENTED">Document attached · declared</option><option value="DISPUTED">Disputed</option></select></label></div><SubjectField {...subjectProps} value={value.subject} onChange={subject => changeRight(value.id, { subject })}/><label>Scope, basis & restrictions<textarea rows={3} maxLength={8000} value={value.scope} placeholder="Who claims or grants what, permitted uses, restrictions, and agreement basis" onChange={event => changeRight(value.id, { scope: event.target.value })}/></label><div className="participation-pair"><label>Territory<input maxLength={1000} value={value.territory} placeholder="Unspecified" onChange={event => changeRight(value.id, { territory: event.target.value })}/></label><label>Term or expiry<input maxLength={2000} value={value.term} placeholder="Unspecified" onChange={event => changeRight(value.id, { term: event.target.value })}/></label></div><label>Jurisdiction<input maxLength={1000} value={value.jurisdiction} placeholder="Unspecified" onChange={event => changeRight(value.id, { jurisdiction: event.target.value })}/></label><EvidenceField assets={retainedAssets} hashes={value.evidenceHashes} onChange={evidenceHashes => changeRight(value.id, { evidenceHashes })}/>{value.status === 'DOCUMENTED' && <small className={!value.evidenceHashes.length ? 'participation-warning' : ''}>{value.evidenceHashes.length ? 'Document recorded for review. Legal validity and consent have not been verified.' : 'Attach a retained supporting document before saving this status.'}</small>}{value.status === 'DISPUTED' && <p className="participation-warning">Disputed claim · resolve or record the disagreement before relying on this right.</p>}</article>)}
            {!data.rights.some(value => value.partyId === party.id) && <p className="participation-empty-note">No rights or consent recorded for this contributor.</p>}<button type="button" className="participation-add" onClick={addRight}>+ Add right or consent</button>
          </>}
        </>}</div>
      </div> : <div className="participation-layout">
        <aside className="participation-index" aria-label="Participation pools"><div className="participation-section-title"><h3>Separate pools</h3><span>{data.pools.length}</span></div>{data.pools.map(value => <button type="button" className="participation-index-item" key={value.id} aria-pressed={pool?.id === value.id} onClick={() => setPoolSelection(value.id)}><strong>{value.name || 'Unnamed pool'}</strong><small>{poolNames[value.kind]}</small></button>)}<button type="button" className="participation-add" onClick={addPool}>+ Add pool</button><p className="participation-aside-note">A point means 1% of the specific pool shown here. Pools are never combined.</p></aside>
        <div className="participation-editor">{!pool ? <div className="participation-empty"><span>02</span><h3>Define the pool first.</h3><p>Name the receipts, defined proceeds, copyright interest or company equity being discussed. Then propose each contributor’s share.</p><button type="button" onClick={addPool}>Add first pool</button></div> : <>
          <div className="participation-section-title"><h3>Pool terms</h3><button type="button" className="participation-remove" onClick={() => update(current => ({ ...current, pools: current.pools.filter(value => value.id !== pool.id) }))}>Remove pool</button></div><div className="participation-pair"><label>Pool name<input maxLength={240} value={pool.name} placeholder="e.g. Film receipts participation" onChange={event => changePool({ name: event.target.value })}/></label><label>Pool type<select value={pool.kind} onChange={event => changePoolKind(event.target.value as ParticipationPool['kind'])}>{Object.entries(poolNames).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label></div><SubjectField {...subjectProps} value={pool.subject} onChange={subject => changePool({ subject })}/>{pool.kind === 'COMPANY_EQUITY' && <label>Legal entity name<input maxLength={240} value={pool.entityName} onChange={event => changePool({ entityName: event.target.value })}/></label>}<label>{pool.kind === 'COMPANY_EQUITY' ? 'Share class & denominator' : pool.kind === 'COPYRIGHT_INTEREST' ? 'Copyright scope & denominator' : 'Pool definition & calculation terms'}<textarea rows={3} maxLength={8000} value={pool.definition} onChange={event => changePool({ definition: event.target.value })} placeholder={pool.kind === 'COMPANY_EQUITY' ? 'State the class, entity and total against which these percentages are proposed' : pool.kind === 'COPYRIGHT_INTEREST' ? 'Describe the specific copyright interest and the whole against which shares are proposed' : 'State included receipts, exclusions, accounting period, permitted deductions and recoupment priority'}/></label>
          <div className="participation-entry"><div className="participation-section-title"><h4>Proposed allocations</h4><span>1 point = 1%</span></div><p className="participation-section-note">Enter each share explicitly. Blank means unknown. Credit, fees and residual obligations remain separate.</p>{pool.allocations.map(allocation => <article className="participation-allocation" key={allocation.id} aria-label={`Allocation for ${partyName(allocation.partyId)}`}><div className="participation-section-title"><h4>{partyName(allocation.partyId)}</h4><button type="button" className="participation-remove" onClick={() => changePool({ allocations: pool.allocations.filter(value => value.id !== allocation.id) })}>Remove allocation</button></div><div className="participation-pair"><NumberField percent label={`Share for ${partyName(allocation.partyId)} (%)`} value={edit?.numbers[`${pool.id}:${allocation.id}`] ?? numberText(allocation.shareBps)} onChange={text => changeNumber(`${pool.id}:${allocation.id}`, text, (current, value) => ({ ...current, pools: current.pools.map(row => row.id === pool.id ? { ...row, allocations: row.allocations.map(item => item.id === allocation.id ? { ...item, shareBps: value } : item) } : row) }))} hint="Percentage of this pool only"/><label>Agreement status<select value={allocation.agreementStatus} onChange={event => changePool({ allocations: pool.allocations.map(value => value.id === allocation.id ? { ...value, agreementStatus: event.target.value as typeof allocation.agreementStatus } : value) })}><option value="PROPOSED">Proposed</option><option value="DOCUMENTED">Document attached · declared</option><option value="DISPUTED">Disputed</option></select></label></div><EvidenceField assets={retainedAssets} hashes={allocation.evidenceHashes} onChange={evidenceHashes => changePool({ allocations: pool.allocations.map(value => value.id === allocation.id ? { ...value, evidenceHashes } : value) })}/>{allocation.agreementStatus === 'DOCUMENTED' && <small className={!allocation.evidenceHashes.length ? 'participation-warning' : ''}>{allocation.evidenceHashes.length ? 'Document recorded, not legally verified.' : 'Attach a retained agreement before saving this status.'}</small>}{allocation.agreementStatus === 'DISPUTED' && <p className="participation-warning">Disputed allocation · scenario figures are for review only.</p>}</article>)}<label>Add contributor to this pool<select value="" onChange={event => { if (event.target.value) changePool({ allocations: [...pool.allocations, { id: crypto.randomUUID(), partyId: event.target.value, shareBps: null, agreementStatus: 'PROPOSED', evidenceHashes: [] }] }); }}><option value="">{data.parties.length ? 'Choose a contributor…' : 'Add contributors in the Contributors tab'}</option>{data.parties.filter(value => !pool.allocations.some(allocation => allocation.partyId === value.id)).map(value => <option key={value.id} value={value.id}>{value.name || 'Unnamed contributor'}</option>)}</select></label></div>
          {(pool.kind === 'RECEIPTS' || pool.kind === 'DEFINED_PROCEEDS') && <div className="participation-entry"><h4>What-if amounts</h4><p className="participation-section-note">Enter normal currency amounts, such as 1000.00. Blank is unknown; enter 0 explicitly when a defined-proceeds deduction or recoupment is zero.</p><label>Scenario currency<select value={pool.currency} onChange={event => changePool({ currency: event.target.value as ParticipationPool['currency'] })}><option value="">Unspecified</option>{['USD', 'CAD', 'EUR', 'GBP'].map(currency => <option key={currency}>{currency}</option>)}</select></label><div className="participation-amounts">{([['receiptsMinor', 'Scenario receipts'], ...(pool.kind === 'DEFINED_PROCEEDS' ? [['deductionsMinor', 'Allowed deductions'], ['recoupmentMinor', 'Recoupment before participation']] : [])] as [keyof Pick<ParticipationPool, 'receiptsMinor' | 'deductionsMinor' | 'recoupmentMinor'>, string][]).map(([key, label]) => <NumberField key={key} label={label} value={edit?.numbers[`${pool.id}:${key}`] ?? numberText(pool[key])} onChange={text => changeNumber(`${pool.id}:${key}`, text, (current, value) => ({ ...current, pools: current.pools.map(row => row.id === pool.id ? { ...row, [key]: value } : row) }))} hint={pool.currency || 'Choose the currency above'}/>)}</div></div>}
          {calculation && <div className="participation-scenario" aria-label="Hypothetical pool result"><div className="participation-section-title"><h4>{pool.kind === 'COPYRIGHT_INTEREST' || pool.kind === 'COMPANY_EQUITY' ? 'Proposed interest' : 'Hypothetical result'}</h4><span>{invalidNumber ? 'Review input' : calculation.status === 'CALCULATED' ? 'Scenario only' : calculation.status === 'INTEREST_ONLY' ? 'Interest only' : calculation.status === 'INVALID' ? 'Review input' : 'Incomplete'}</span></div><div className="participation-share-strip"><span><strong>{numberText(calculation.allocatedBps)}%</strong> specified</span><span><strong>{numberText(calculation.unallocatedBps)}%</strong> not specified</span></div>{!invalidNumber && calculation.status === 'CALCULATED' ? <><dl><div><dt>Receipts after defined deductions</dt><dd>{money(calculation.baseMinor, pool.currency)}</dd></div><div><dt>Applied recoupment</dt><dd>{money(calculation.appliedRecoupmentMinor, pool.currency)}</dd></div><div className="participation-available"><dt>Available pool · percentage denominator</dt><dd>{money(calculation.availableMinor, pool.currency)}</dd></div>{calculation.unrecoveredMinor !== null && calculation.unrecoveredMinor > 0 && <div><dt>Unrecovered amount</dt><dd>{money(calculation.unrecoveredMinor, pool.currency)}</dd></div>}</dl><table><caption>Each share applies to {money(calculation.availableMinor, pool.currency)} available in this pool.</caption><thead><tr><th>Contributor</th><th>Share</th><th>Hypothetical amount</th></tr></thead><tbody>{calculation.payouts.map(value => <tr key={value.partyId}><td>{partyName(value.partyId)}</td><td>{numberText(pool.allocations.find(allocation => allocation.partyId === value.partyId)?.shareBps ?? null)}%</td><td>{money(value.amountMinor, pool.currency)}</td></tr>)}</tbody></table><dl><div><dt>Unallocated share amount</dt><dd>{money(calculation.unallocatedMinor, pool.currency)}</dd></div><div><dt>Rounding remainder</dt><dd>{money(calculation.roundingMinor, pool.currency)}</dd></div></dl></> : <p>{invalidNumber ? 'Correct the highlighted numeric input to calculate this draft.' : calculation.status === 'INTEREST_ONLY' ? 'These declared percentages describe an interest only. They do not issue equity, transfer copyright or calculate a payout.' : 'Complete the pool definition, all shares, currency and required amounts to calculate. No unknown value is assumed to be zero.'}</p>}{calculation.status === 'INVALID' && <p className="participation-warning">{calculation.errors.join(' ')}</p>}<small>Illustrative arithmetic only. No amount is due, paid or settled by this draft. Individual amounts round down to the smallest currency unit; the remainder stays visible.</small></div>}
        </>}</div>
      </div>}
    </fieldset>
    <div className="participation-authority"><p>Authored claims and proposals for review. An attached document is recorded evidence, not verified ownership or consent. Saving grants no rights and issues no equity.</p></div>
    {invalid && <p role="alert">{invalid}</p>}{referenceError && <p role="alert">{referenceError}</p>}{ownFeedback?.error && <p role="alert">{ownFeedback.error}</p>}{ownFeedback?.notice && <p role="status">{ownFeedback.notice}</p>}
    <footer className="participation-footer"><button type="button" className="primary" disabled={working || Boolean(invalid) || Boolean(referenceError) || (!dirty && Boolean(saved))} onClick={() => void save()}>{working ? 'Working…' : 'Save participation draft'}</button><button type="button" disabled={working || Boolean(invalid)} onClick={() => void exportDraft()}>Export draft packet</button>{dirty && <button type="button" disabled={working} onClick={() => { if (window.confirm('Discard unsaved participation edits and return to the latest loaded draft?')) { setEdits(previous => { const next = { ...previous }; delete next[scope]; return next; }); setFeedback(undefined); } }}>Discard edits</button>}<small>{dirty ? 'Unsaved draft' : saved ? `Saved locally · version ${saved.version}` : 'Draft only'}</small></footer>
  </section>;
}
