import { useEffect, useMemo, useState, useRef } from 'react';
import { ArrowUpRight, BookOpen, Download, File, Film, Image, Music, LayoutGrid, List, RefreshCw, Search } from 'lucide-react';
import type { LoreSource, Project, WorkspaceProject, WorkspaceRecord } from './types';
import { projectLibraryApi, type ProjectLibraryApi } from './projectLibraryApi';
import { FILE_REVIEW_STATES, fileReviewLabel, fileReviewStates, familyLabel, fileSize, projectFileEntries, retainedRecordMatchesProject, projectInventoryCsv, ORGANIZATION_STATUSES, organizationLabel, originLabel, PROJECT_FILE_ORIGINS, PROJECT_FILE_FAMILIES, type AssetCurationRecord, type AssetUsage, type ProjectLibraryCatalog } from './projectLibraryModel';
import AssetOrganizationPanel from './AssetOrganizationPanel';
import type { AssetMarketProfile } from './types';
import AssetMarketPanel from './AssetMarketPanel';
import ParsedAssetSearch from './ParsedAssetSearch';
import { downloadLocalBlob } from './localDownload';
import LibraryMediaReview from './LibraryMediaReview';
import AssetWorldContext from './AssetWorldContext';
import PreservationIntegrityPanel from './PreservationIntegrityPanel';
import ProjectParticipationPanel from './ProjectParticipationPanel';
import type { UniverseCatalog } from './universeApi';
import './project-library.css';

export default function ProjectLibraryPanel({ project, records, open, onReadLore, onSaved, onDirty, onOpenUsage, onOpenBudget, universe, universeLoading, universeError, onOpenWorld, assetRequest, libraryApi = projectLibraryApi }: { project: WorkspaceProject; records: WorkspaceRecord[]; open: boolean; onReadLore(id: string, pageNumber?: number, citation?: { sha256: string; textSha256?: string }): void; onSaved?(record: WorkspaceRecord): void; onDirty?(dirty: boolean): void; onOpenUsage?(usage: AssetUsage): void; onOpenBudget?(targetId?: string): void; libraryApi?: ProjectLibraryApi; universe?: UniverseCatalog; universeLoading?: boolean; universeError?: string; onOpenWorld?(entityId: string): void; assetRequest?: { sha256: string; nonce: number } }) {
  const scenes: Project['scenes'] = project.scenes;
  const scope = `${project.id}:${project.sourceHash}`;
  const [importing, setImporting] = useState(false), [importNotice, setImportNotice] = useState('');
  const fileInput = useRef<HTMLInputElement>(null), importingRef = useRef(false);
  const currentScope = useRef(scope); currentScope.current = scope;
  const alive = useRef(true); useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  async function importFiles(files: File[]) {
    if (!libraryApi.importFile || importingRef.current || !files.length) return;
    importingRef.current = true; setImporting(true); setError(''); setImportNotice(''); const captured = scope; let imported = 0;
    try {
      for (const file of files) {
        if (!alive.current || currentScope.current !== captured) break;
        const record = await libraryApi.importFile(project, file);
        if (!alive.current || currentScope.current !== captured) break;
        onSaved?.(record); imported++; setImportNotice(`${imported} of ${files.length} files retained`);
      }
    } catch (caught) { if (alive.current && currentScope.current === captured) setError(`${caught instanceof Error ? caught.message : 'Import not confirmed.'} ${imported} files were retained. Retrying will not duplicate matching files.`); }
    finally { importingRef.current = false; if (alive.current && currentScope.current === captured) { setImporting(false); setRefresh(value => value + 1); } }
  }
  const [snapshot, setSnapshot] = useState<{ scope: string; catalog: ProjectLibraryCatalog }>();
  const [query, setQuery] = useState(''), [family, setFamily] = useState(''), [collection, setCollection] = useState(''), [category, setCategory] = useState('');
  const [organization, setOrganization] = useState(''), [origin, setOrigin] = useState('');
  const [reviewState, setReviewState] = useState(''), [sceneFilter, setSceneFilter] = useState(''), [view, setView] = useState<'grid'|'list'>('grid');
  const [inspectorTab, setInspectorTab] = useState<'organize'|'market'>('organize');
  const [preservationOpen, setPreservationOpen] = useState(false);
  const [participationOpen, setParticipationOpen] = useState(false), [participationDirty, setParticipationDirty] = useState(false);
  const participationSection = useRef<HTMLDivElement>(null);
  const [organizationDirty, setOrganizationDirty] = useState(false), [marketDirty, setMarketDirty] = useState(false), [measurementBusy, setMeasurementBusy] = useState(false);
  useEffect(() => { onDirty?.(organizationDirty || marketDirty || participationDirty || measurementBusy || importing); }, [organizationDirty, marketDirty, participationDirty, measurementBusy, importing, onDirty]);
  const [selectedHash, setSelectedHash] = useState(''), [loading, setLoading] = useState(false), [error, setError] = useState(''), [refresh, setRefresh] = useState(0);
  const basis = records.filter(record => ['asset-token-preparation', 'asset-market-profile', 'project-participation', 'project-asset', 'lore-source', 'asset-curation', 'storyboard-cell', 'shot-keyframes', 'comic-draft', 'comic-package'].includes(record.kind)).map(record => `${record.id}:${record.sha256}`).sort().join('|');
  useEffect(() => { setQuery(''); setFamily(''); setCollection(''); setCategory(''); setOrganization(''); setOrigin(''); setReviewState(''); setSceneFilter(''); setSelectedHash(''); setPreservationOpen(false); setParticipationOpen(false); }, [scope]);
  useEffect(() => {
    if (!open) return;
    const controller = new AbortController(); let active = true;
    setLoading(true); setError('');
    void libraryApi.load(project, controller.signal).then(catalog => { if (active) setSnapshot({ scope, catalog }); }).catch(caught => { if (active) setError(caught instanceof Error ? caught.message : 'The local project library did not respond.'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; controller.abort(); };
  }, [open, scope, basis, refresh, libraryApi, project]);
  const catalog = snapshot?.scope === scope ? snapshot.catalog : undefined;
  const entries = useMemo(() => projectFileEntries(catalog, records, project.sourceHash, project.id, project), [catalog, records, project]);
  useEffect(() => {
    if (!assetRequest) return;
    setSelectedHash(assetRequest.sha256); setQuery(''); setFamily(''); setCollection(''); setCategory(''); setOrganization(''); setOrigin(''); setReviewState(''); setSceneFilter('');
  }, [assetRequest]);
  const marketProfiles = records.filter(record => record.kind === 'asset-market-profile' && retainedRecordMatchesProject(record, project));
  const selected = entries.find(entry => entry.sha256 === selectedHash);
  const visible = entries.filter(entry => (!reviewState || fileReviewStates(entry).some(value => value === reviewState)) && (!sceneFilter || entry.curation?.data.sceneIds.includes(sceneFilter) || entry.provenance?.some(item => item.sceneIds.includes(sceneFilter))) && (!family || entry.family === family) && (!collection || entry.collection === collection) && (!category || entry.category === category) && (!origin || entry.provenance?.some(item => item.origin === origin)) && (!organization || Boolean(entry.asset) && (entry.curation?.data.organizationStatus ?? 'INBOX') === organization) && `${entry.title} ${entry.filename} ${entry.category} ${entry.collection} ${entry.curation?.data.tags.join(' ') ?? ''} ${entry.curation?.data.notes ?? ''} ${(entry.asset?.data.sourcePaths ?? []).join(' ')} ${(entry.provenance ?? []).map(item => `${item.filename} ${originLabel(item.origin)} ${item.status} ${item.sceneIds.map(id => scenes.find(scene => scene.id === id)?.heading ?? id).join(' ')}`).join(' ')} ${(entry.takes ?? []).map(take => scenes.find(scene => scene.id === take.sceneId)?.shots.find(shot => shot.id === take.shotId)?.label ?? '').join(' ')}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const collections = [...new Set(entries.map(entry => entry.collection))].sort(), categories = [...new Set(entries.map(entry => entry.category))].sort();
  const lore = entries.flatMap(entry => entry.lore), pages = lore.reduce((sum, record) => sum + ((record.data as LoreSource).extraction?.pageCount ?? 0), 0);
  function retainCuration(record: AssetCurationRecord) {
    setSnapshot(previous => previous?.scope === scope ? { ...previous, catalog: { ...previous.catalog, assets: previous.catalog.assets.map(asset => asset.record.id === record.data.assetRef.id ? { ...asset, curation: record } : asset) } } : previous);
    onSaved?.(record);
  }
  function locateUsage(usage: AssetUsage) {
    if (usage.record.kind !== 'project-participation') { onOpenUsage?.(usage); return; }
    const current = records.find(record => record.id === usage.record.id && record.version === usage.record.version && record.sha256 === usage.record.sha256 && retainedRecordMatchesProject(record, project));
    if (!current) { setError('The participation ledger changed. Refresh files before opening this reference.'); return; }
    setParticipationOpen(true);
    requestAnimationFrame(() => participationSection.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }));
  }
  return <section className="project-file-library" aria-label="Whole project files" hidden={!open}>
    <header className="pfl-heading"><div><span className="eyebrow">PROJECT ASSETS</span><h2>{project.title}</h2><p>{project.sourceHash === null ? 'Screenplays, research, reference budgets and table reads for development.' : 'Originals, measured takes, generated results and comic drafts in one working library.'}</p></div><div className="pfl-header-actions">{libraryApi.importFile && <><input ref={fileInput} type="file" multiple hidden aria-label="Import development files" onChange={event => { const files = Array.from(event.target.files ?? []); event.target.value = ''; void importFiles(files); }}/><button className="primary" disabled={importing} onClick={() => fileInput.current?.click()}>{importing ? 'Importing…' : 'Import files'}</button></>}<button className="secondary" disabled={!visible.length} onClick={() => downloadLocalBlob(new Blob([projectInventoryCsv(visible)], { type: 'text/csv;charset=utf-8' }), 'caniscreenwrite-asset-inventory.csv')}><Download size={14}/>Export inventory</button><button className="secondary" disabled={loading} onClick={() => setRefresh(value => value + 1)}><RefreshCw size={14}/>Refresh files</button></div></header>
    {importNotice && <p role="status">{importNotice}</p>}
    {error && <p className="error-bar" role="alert">{error} Files from loaded workspace records remain available below.</p>}
    <div className="pfl-summary" role="status">{loading ? 'Reading retained project files…' : `${entries.length} unique retained files · ${collections.length} collections`}{error && ' · file catalog refresh failed'}</div>
    <p className="pfl-catalog-count">{entries.filter(entry => marketProfiles.some(record => (record.data as AssetMarketProfile).assetHash === entry.sha256)).length}/{entries.length} files have saved market drafts · rights review remains separate</p>
    {catalog && <p className="pfl-catalog-count">{catalog.assets.length} imported project files · matching lore originals appear once in the list.</p>}
    <div className="pfl-inventory-line"><span>{fileSize(entries.reduce((sum, entry) => sum + entry.byteLength, 0))} retained</span><span>{lore.length} readable source records</span><span>{pages.toLocaleString()} PDF page records</span><span>{entries.filter(entry => entry.curation?.data.organizationStatus === 'SHORTLIST').length} shortlisted</span></div>
    <div className="pfl-view-controls"><button className="secondary" aria-expanded={participationOpen} aria-controls="library-participation" onClick={() => setParticipationOpen(value => !value)}>Contributors, rights &amp; points</button><span>Connect people, creative work, agreements and business shares.</span></div>
    <div id="library-participation" ref={participationSection}><ProjectParticipationPanel key={scope} project={project} records={records} assets={entries.map(entry => ({ sha256: entry.sha256, title: entry.title, mimeType: entry.mimeType }))} open={open && participationOpen} onSaved={onSaved} onDirty={setParticipationDirty} onOpenBudget={onOpenBudget}/></div>
    <div className="pfl-view-controls"><button className="secondary" aria-expanded={preservationOpen} aria-controls="library-preservation" onClick={() => setPreservationOpen(value => !value)}>Preservation & integrity</button><span>Check retained files and keep dated evidence for your production plan.</span></div>
    <div id="library-preservation" hidden={!preservationOpen}><PreservationIntegrityPanel key={scope} project={project} open={open && preservationOpen} onOpenBudget={onOpenBudget ? () => onOpenBudget(`project:${project.id}`) : undefined}/></div>
    {project.sourceHash !== null && <ParsedAssetSearch project={project as Project} api={libraryApi} onReadLore={onReadLore}/>}
    <div className="pfl-review-overview" aria-label="Video readiness">{FILE_REVIEW_STATES.map(value => <button key={value} aria-pressed={reviewState === value} onClick={() => setReviewState(prior => prior === value ? '' : value)}><strong>{entries.filter(entry => fileReviewStates(entry).includes(value)).length}</strong><span>{fileReviewLabel(value)}</span></button>)}</div>
    <div className="pfl-filters pfl-primary-filters"><label className="pfl-search"><Search size={15}/><input aria-label="Find a project file" type="search" placeholder="Find a file, scene, shot or tag" value={query} onChange={event => setQuery(event.target.value)}/></label><label>Collection<select aria-label="Project file collection" value={collection} onChange={event => setCollection(event.target.value)}><option value="">All collections</option>{collections.map(value => <option key={value}>{value}</option>)}</select></label><label>Type<select aria-label="Project file type" value={family} onChange={event => setFamily(event.target.value)}><option value="">All types</option>{PROJECT_FILE_FAMILIES.filter(value => entries.some(entry => entry.family === value)).map(value => <option key={value} value={value}>{familyLabel(value)}</option>)}</select></label></div>
    <div className="pfl-filters pfl-context-filters" role="group" aria-label="Asset source and review filters"><label>Origin<select aria-label="Project file origin" value={origin} onChange={event => setOrigin(event.target.value)}><option value="">All retained files</option>{PROJECT_FILE_ORIGINS.filter(value => entries.some(entry => entry.provenance?.some(item => item.origin === value))).map(value => <option key={value} value={value}>{originLabel(value)}</option>)}</select></label><label>Category<select aria-label="Project file category" value={category} onChange={event => setCategory(event.target.value)}><option value="">All categories</option>{categories.map(value => <option key={value}>{value}</option>)}</select></label><label>Organization<select aria-label="Asset organization filter" value={organization} onChange={event => setOrganization(event.target.value)}><option value="">All assets</option>{ORGANIZATION_STATUSES.map(value => <option key={value} value={value}>{organizationLabel(value)}</option>)}</select></label><label>Scene<select aria-label="Project file scene" value={sceneFilter} onChange={event => setSceneFilter(event.target.value)}><option value="">All scenes</option>{scenes.map(scene => <option key={scene.id} value={scene.id}>Scene {scene.index} · {scene.heading}</option>)}</select></label><label>Video review<select aria-label="Project file review state" value={reviewState} onChange={event => setReviewState(event.target.value)}><option value="">All review states</option>{FILE_REVIEW_STATES.map(value => <option key={value} value={value}>{fileReviewLabel(value)}</option>)}</select></label></div>
    <div className="pfl-view-controls" aria-label="Library display"><span>{visible.length} of {entries.length} files</span><button aria-label="Asset grid" aria-pressed={view === 'grid'} onClick={() => setView('grid')}><LayoutGrid size={15}/>Grid</button><button aria-label="Asset list" aria-pressed={view === 'list'} onClick={() => setView('list')}><List size={15}/>List</button>{(query || family || collection || category || organization || origin || sceneFilter || reviewState) && <button onClick={() => { setQuery(''); setFamily(''); setCollection(''); setCategory(''); setOrganization(''); setOrigin(''); setSceneFilter(''); setReviewState(''); }}>Clear filters</button>}</div>
    <div className="pfl-layout"><div className="pfl-file-list" data-view={view} aria-label="Project file results"><div className="pfl-list-heading"><span>{visible.length} {visible.length === 1 ? 'file' : 'files'}</span><span>Type / size</span></div>{visible.map(entry => <button key={entry.sha256} className="pfl-file" title={entry.title} disabled={measurementBusy && selected?.sha256 !== entry.sha256} aria-pressed={selected?.sha256 === entry.sha256} onClick={() => setSelectedHash(entry.sha256)}><span className="pfl-file-thumb" data-family={entry.family}>{entry.family === 'IMAGE' && ['image/png','image/jpeg','image/gif','image/webp'].includes(entry.mimeType) ? <img src={entry.downloadUrl} alt="" loading="lazy"/> : entry.family === 'VIDEO' ? <Film size={26} aria-hidden="true"/> : entry.family === 'AUDIO' ? <Music size={26} aria-hidden="true"/> : entry.family === 'IMAGE' ? <Image size={26} aria-hidden="true"/> : entry.family === 'DOCUMENT' ? <BookOpen size={26} aria-hidden="true"/> : <File size={26} aria-hidden="true"/>}{entry.family === 'VIDEO' && <span>{entry.takes?.length ? `${(entry.takes[0].measurement.durationMs / 1000).toFixed(1)} s` : 'To measure'}</span>}</span><span><strong>{entry.title}</strong><small>{entry.filename}</small><span>{entry.collection} · {entry.category}{entry.curation && ` · ${organizationLabel(entry.curation.data.organizationStatus)}`}{entry.curation?.data.tags.length ? ` · ${entry.curation.data.tags.join(', ')}` : ''}</span></span><span className="pfl-file-meta">{familyLabel(entry.family)}{fileReviewStates(entry).length > 0 && <small className="pfl-card-review">{fileReviewStates(entry).map(fileReviewLabel).join(' · ')}</small>}<small>{fileSize(entry.byteLength)}</small></span></button>)}{!loading && !visible.length && <p className="pfl-empty">{entries.length ? 'No files match these filters.' : 'No retained files yet. Imported project files will appear here after their original bytes are verified.'}</p>}</div>
    <aside className="pfl-inspector" aria-label="Project file details">
      {selected ? <><span className="eyebrow">RETAINED FILE</span><h3>{selected.title}</h3><p className="pfl-filename">{selected.filename}</p>{onOpenBudget && <button className="secondary" onClick={() => onOpenBudget(`asset:${selected.sha256}`)}>Asset costs</button>}<button className="secondary" onClick={() => { setParticipationOpen(true); requestAnimationFrame(() => participationSection.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })); }}>Contributors &amp; rights</button>
        {selected.family === 'IMAGE' && ['image/png','image/jpeg','image/gif','image/webp'].includes(selected.mimeType) && <img className="pfl-preview" src={selected.downloadUrl} alt={`${selected.title} retained original`} loading="lazy"/>}
        {selected.family === 'VIDEO' && <video className="pfl-preview" key={selected.sha256} src={selected.downloadUrl} controls preload="metadata" aria-label={`Preview ${selected.title}`}/>}
        {selected.family === 'AUDIO' && <audio className="pfl-audio" key={selected.sha256} src={selected.downloadUrl} controls preload="none" aria-label={`Listen to ${selected.title}`}/>}
        <dl><div><dt>Collection</dt><dd>{selected.collection}</dd></div><div><dt>Type</dt><dd>{familyLabel(selected.family)} · {fileSize(selected.byteLength)}</dd></div></dl>
        <section className="pfl-origins" aria-label="Retained file provenance"><h4>Origin & review status</h4>{selected.provenance?.map((item, index) => <div key={`${item.record?.id ?? item.retainedReturn.id}:${item.filename}:${index}`}><strong>{originLabel(item.origin)}</strong><p>{item.status}</p>{item.filename !== selected.filename && <small>{item.filename}</small>}{item.detail && <small>{item.detail}</small>}<details><summary>{item.record ? `Saved source record · v${item.record.version}` : 'Retained rehearsal receipt'}</summary><code>{item.record?.id ?? item.retainedReturn.id}<br/>{item.record?.sha256 ?? item.retainedReturn.sha256}</code></details></div>)}</section>
        {selected.family === 'VIDEO' && selected.asset && !selected.provenance?.some(item => item.origin === 'MEASURED_TAKE') && <p className="pfl-scope">This video is a project reference. Measure it below to connect it to scene footage and review its take.</p>}
        {project.sourceHash !== null && <LibraryMediaReview key={`${scope}:${selected.sha256}`} project={project as Project} entry={selected} records={records} onSaved={onSaved} onOpenUsage={onOpenUsage} onBusyChange={setMeasurementBusy}/>}
        {project.sourceHash !== null && <AssetWorldContext project={project as Project} entry={selected} universe={universe} loading={universeLoading} error={universeError} onOpenWorld={onOpenWorld} onReadLore={onReadLore}/>}
        <a className="secondary pfl-download" href={selected.downloadUrl} download={selected.filename}><Download size={14}/>{selected.asset || selected.lore.length ? 'Save original file' : 'Save retained file'}<ArrowUpRight size={13}/></a>
      </> : <><BookOpen size={30} aria-hidden="true"/><h3>Your project’s working library.</h3><p>Select an asset to preview it, organize it, inspect parsed information and trace its saved uses.</p><p className="pfl-scope">Original files, extracted pages, writing drafts and measured footage retain their own identities.</p></>}
      {selected && <nav className="pfl-inspector-tabs" aria-label="Asset inspector"><button aria-pressed={inspectorTab === 'organize'} onClick={() => setInspectorTab('organize')}>Organize & trace</button><button aria-pressed={inspectorTab === 'market'} onClick={() => setInspectorTab('market')}>Market preparation</button></nav>}
      <div hidden={inspectorTab !== 'organize'}><AssetOrganizationPanel project={project} entry={selected} api={libraryApi} records={records} onSaved={retainCuration} onDirty={setOrganizationDirty} onOpenUsage={locateUsage}/></div>
      <AssetMarketPanel project={project} asset={selected ? {sha256:selected.sha256,title:selected.title,mimeType:selected.mimeType} : undefined} parentHashes={selected?.parentAssetHashes} assets={entries.map(entry => ({sha256:entry.sha256,title:entry.title,mimeType:entry.mimeType}))} records={records} onSaved={onSaved} onDirty={setMarketDirty} open={inspectorTab === 'market'}/>
      {selected && <>{selected.lore.length > 0 ? <section className="pfl-reading"><h4>Parsed information</h4>{selected.lore.map(record => { const source = record.data as LoreSource, extraction = selected.extraction?.sources.find(item => item.ref.id === record.id); return <div key={record.id}><button className="secondary" onClick={() => onReadLore(record.id)}><BookOpen size={14}/><span>{source.title}<small>{source.documentType === 'PDF' ? `${source.extraction?.pageCount ?? 0} verified page records` : 'Original image reference'}</small></span><ArrowUpRight size={13}/></button>{extraction && <p className="pfl-scope">{extraction.pagesWithText} pages with text · {extraction.textCharacters.toLocaleString()} characters · {extraction.ocrPerformed ? 'OCR recorded' : 'No OCR recorded'}</p>}</div>; })}</section> : <p className="pfl-scope">No extracted reader is linked to this file. The original opens in its supported application after download.</p>}
        <details className="pfl-provenance"><summary>File locations & identity</summary><h4>Retained in workspace</h4><p>blobs/{selected.sha256}</p>{selected.asset && <><h4>Organized copy · relative to Library/</h4><p>{selected.asset.data.collectionPath}</p><p>Recorded collection location. The app reads the retained workspace copy; this is not a live folder check.</p><h4>Original source locations</h4><ul>{selected.asset.data.sourcePaths.map(path => <li key={path}>{path}</li>)}</ul></>}<h4>File SHA-256</h4><code>{selected.sha256}</code></details>
      </>}
    </aside></div>
  </section>;
}
