import { useMemo, useState } from 'react';
import { buildScriptAnalysis, SCRIPT_ANALYSIS_LIMIT, scriptAnalysisCsv, scriptAnalysisScope, type ScriptReportKind } from './scriptAnalysisModel';
import { downloadLocalBlob } from './localDownload';
import './script-analysis.css';

export interface ScriptAnalysisProps { body: string; title: string; dirty?: boolean; savedVersion?: number; onScene?: (sceneIndex: number) => void; onWrite?: () => void }
const PAGE = 20;

/** Visual thesis: ink/ivory, readable character distribution beside exact dialogue.
 * Content: draft basis → selected character evidence → shared scenes → scene index.
 * Interaction: quiet row hover, selected-row emphasis, progressive evidence reveal.
 */
export default function ScriptAnalysis({ body, title, dirty = false, savedVersion, onScene, onWrite }: ScriptAnalysisProps) {
  const analysis = useMemo(() => buildScriptAnalysis(body), [body]);
  const [selected, setSelected] = useState<string | null>(null), [query, setQuery] = useState('');
  const [characterLimit, setCharacterLimit] = useState(PAGE), [sceneLimit, setSceneLimit] = useState(PAGE), [lineLimit, setLineLimit] = useState(8), [relationshipLimit, setRelationshipLimit] = useState(PAGE);
  const [locationLimit, setLocationLimit] = useState(PAGE);
  const [exportResult, setExportResult] = useState<{ body: string; title: string; scope: string; text: string; failed: boolean } | null>(null);
  const character = analysis.characters.find(item => item.name === selected) ?? analysis.characters[0];
  const characters = analysis.characters.filter(item => item.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const relationships = analysis.relationships.filter(item => !character || item.characters.includes(character.name));
  const scope = scriptAnalysisScope(dirty, savedVersion);
  const sceneLink = (index: number, label = `Scene ${index}`) => onScene ? <button type="button" className="analysis-link" onClick={() => onScene(index)}>{label} ↗</button> : <span>{label}</span>;
  function exportReport(kind: ScriptReportKind) {
    try {
      const csv = scriptAnalysisCsv(kind, analysis, { title, dirty, savedVersion });
      const filename = (title.replace(/[^\p{L}\p{N}._ -]/gu, '_').slice(0, 120).trim() || 'screenplay') + `-${kind}.csv`;
      downloadLocalBlob(new Blob([csv], { type: 'text/csv;charset=utf-8' }), filename);
      setExportResult({ body, title, scope, text: `${kind[0].toUpperCase() + kind.slice(1)} report prepared · ${scope}. Complete the Save dialog.`, failed: false });
    } catch (error) { setExportResult({ body, title, scope, text: error instanceof Error ? error.message : 'The report could not be exported.', failed: true }); }
  }
  return <section className="script-analysis" aria-label="Local script analysis">
    <header className="analysis-heading"><div><p className="analysis-eyebrow">SCRIPT ANALYSIS / LOCAL</p><h2>{title || 'Untitled writing draft'}</h2><p role="status">{scope}</p></div>{onWrite && <button type="button" className="secondary" onClick={onWrite}>Return to Write ↗</button>}</header>
    {analysis.status === 'TOO_LONG' ? <p role="alert">This draft exceeds the {SCRIPT_ANALYSIS_LIMIT.toLocaleString()} character analysis limit. Open a shorter separate draft to inspect it. Your writing is unchanged.</p> : analysis.status === 'EMPTY' ? <div className="analysis-empty"><h3>Start with a scene</h3><p>Open or write a Fountain draft to inspect its characters and dialogue here.</p></div> : <>
      <p className="analysis-summary"><strong>{analysis.scenes.length}</strong> recognized scenes · <strong>{analysis.characters.length}</strong> speaking characters · <strong>{analysis.dialogueLines}</strong> dialogue lines · <strong>{analysis.dialogueWords}</strong> dialogue words</p>
      <p className="analysis-scope">Observations from recognized Fountain cues. A dialogue line is one nonblank text line after a cue; parentheticals are excluded. Shared scenes describe speaking appearances, not relationships inferred from the story.</p>
      {!analysis.scenes.length ? <div className="analysis-empty"><h3>Add a scene heading to locate observations</h3><p>Use INT. ROOM - DAY, EXT. ROAD - NIGHT, or a forced heading beginning with a period. Title text and opening notes remain outside scene analysis.</p></div> : <>
        <section className="analysis-reports" aria-label="Export writing breakdowns"><h3>Export writing breakdowns</h3><p>Use these CSV reports for casting and location planning. Each row names this draft and its save status. Speaking cues are observations, not the full cast; these reports do not establish page counts or running time.</p><div className="analysis-report-actions"><button type="button" className="secondary" disabled={!analysis.characters.length} onClick={() => exportReport('characters')}>Character CSV</button><button type="button" className="secondary" onClick={() => exportReport('scenes')}>Scene CSV</button><button type="button" className="secondary" onClick={() => exportReport('locations')}>Location CSV</button></div><small>All recognized scenes are included, regardless of the visible filters. Formula-like text is prefixed with an apostrophe in the report for spreadsheet safety.</small>{exportResult?.body === body && exportResult.title === title && exportResult.scope === scope && <p role={exportResult.failed ? 'alert' : 'status'}>{exportResult.text}</p>}</section>
        <div className="analysis-character-workspace"><section aria-label="Character dialogue distribution"><div className="analysis-section-heading"><h3>Who speaks</h3><span>Share of dialogue lines</span></div><label className="analysis-search">Find a character<input type="search" value={query} onChange={event => { setQuery(event.target.value); setCharacterLimit(PAGE); }} placeholder="Character name"/></label>
          <div className="analysis-characters">{characters.slice(0, characterLimit).map(item => <button type="button" key={item.name} className="analysis-character" aria-pressed={character?.name === item.name} onClick={() => { setSelected(item.name); setLineLimit(8); setRelationshipLimit(PAGE); }}><span className="analysis-character-label"><strong>{item.name}</strong><span>{item.dialogueShare}%</span></span><span className="analysis-bar" aria-hidden="true"><span style={{ width: `${item.dialogueShare}%` }}/></span><small>{item.dialogueLines} lines · {item.sceneIndices.length} scenes · {item.words} words</small></button>)}</div>
          {!characters.length && <p className="analysis-muted">{analysis.characters.length ? 'No character matches this search.' : 'No speaking character cues were recognized.'}</p>}{characters.length > characterLimit && <button type="button" className="analysis-link" onClick={() => setCharacterLimit(value => value + PAGE)}>Show more characters ({characters.length - characterLimit})</button>}
        </section><section className="analysis-character-detail" aria-label="Selected character observations">{character ? <><div className="analysis-section-heading"><h3>{character.name}</h3><span>{character.averageLineCharacters} characters per dialogue line on average</span></div><p className="analysis-location-list">Speaking in {character.sceneIndices.length} {character.sceneIndices.length === 1 ? 'scene' : 'scenes'}: {character.sceneIndices.slice(0, 12).map(index => <span key={index}>{sceneLink(index)}</span>)}{character.sceneIndices.length > 12 && <span>and {character.sceneIndices.length - 12} more below</span>}</p>
          <h4>Repeated phrases</h4>{character.repeatedPhrases.length ? <><p className="analysis-muted">Repeated sequences of 3–6 words, ignoring case and punctuation. Overlapping occurrences count separately.</p><ul className="analysis-phrases">{character.repeatedPhrases.map(item => <li key={item.phrase}><q>{item.phrase}</q><span>{item.count} occurrences</span><span>{item.sceneIndices.slice(0, 4).map(index => <span key={index}>{sceneLink(index)}</span>)}{item.sceneIndices.length > 4 && <small> +{item.sceneIndices.length - 4} scenes</small>}</span></li>)}</ul></> : <p className="analysis-muted">No repeated phrase of 3–6 words found for this character.</p>}
          <h4>Dialogue in the draft</h4><ol className="analysis-dialogue">{character.dialogue.slice(0, lineLimit).map(item => <li key={item.start}><div>{sceneLink(item.sceneIndex)}<span>Line {item.line}</span></div><blockquote>{item.text}</blockquote></li>)}</ol>{character.dialogue.length > lineLimit && <button type="button" className="analysis-link" onClick={() => setLineLimit(value => value + 12)}>Show more dialogue ({character.dialogue.length - lineLimit})</button>}
        </> : <p className="analysis-muted">Recognized speaking characters appear here. Character mentions in action do not count as dialogue.</p>}</section></div>
        <section className="analysis-locations" aria-label="Locations and settings"><details><summary>Locations & settings · {analysis.locations.length}</summary><p className="analysis-muted">Standard headings are grouped by location text, ignoring case. The final spaced dash separates a time label; confirm unusual headings. Forced headings stay whole and separate. These are writing labels, not approved locations or canon identities.</p><div className="analysis-table-scroll"><table><caption className="analysis-visually-hidden">Locations from draft scene headings</caption><thead><tr><th scope="col">Setting</th><th scope="col">INT / EXT</th><th scope="col">Time labels</th><th scope="col">Scenes</th></tr></thead><tbody>{analysis.locations.slice(0, locationLimit).map(row => <tr key={JSON.stringify([row.forced, row.location.toUpperCase()])}><th scope="row">{row.location}{row.forced && <small className="analysis-heading-kind">Forced heading · unsplit</small>}</th><td>{row.intExt.join(' / ') || 'Unspecified'}</td><td>{row.times.join(', ') || 'Unspecified'}</td><td>{row.sceneIndices.slice(0, 8).map(index => <span key={index}>{sceneLink(index)}</span>)}{row.sceneIndices.length > 8 && <details><summary>{row.sceneIndices.length - 8} more scenes</summary>{row.sceneIndices.slice(8).map(index => <span key={index}>{sceneLink(index)}</span>)}</details>}</td></tr>)}</tbody></table></div>{analysis.locations.length > locationLimit && <button type="button" className="analysis-link" onClick={() => setLocationLimit(value => value + PAGE)}>Show more settings ({analysis.locations.length - locationLimit})</button>}</details></section>
        <section className="analysis-relationships" aria-label="Shared speaking scenes"><div className="analysis-section-heading"><h3>{character ? `Shared scenes · ${character.name}` : 'Shared scenes'}</h3><span>Co-occurrence in the same recognized scene</span></div>{!analysis.relationshipsComplete ? <p role="status">The draft has more than 20,000 scene-pair combinations. Relationship analysis is unavailable for this size; character and scene observations above remain complete.</p> : relationships.length ? <><div className="analysis-table-scroll"><table><caption className="analysis-visually-hidden">Character pairs and the scenes where both have dialogue</caption><thead><tr><th scope="col">Characters</th><th scope="col">Shared scenes</th><th scope="col">Open scene</th></tr></thead><tbody>{relationships.slice(0, relationshipLimit).map(item => <tr key={JSON.stringify(item.characters)}><th scope="row">{item.characters.join(' / ')}</th><td>{item.sceneIndices.length}</td><td>{item.sceneIndices.slice(0, 8).map(index => <span key={index}>{sceneLink(index)}</span>)}{item.sceneIndices.length > 8 && <details><summary>{item.sceneIndices.length - 8} more</summary>{item.sceneIndices.slice(8).map(index => <span key={index}>{sceneLink(index)}</span>)}</details>}</td></tr>)}</tbody></table></div>{relationships.length > relationshipLimit && <button type="button" className="analysis-link" onClick={() => setRelationshipLimit(value => value + PAGE)}>Show more pairs ({relationships.length - relationshipLimit})</button>}</> : <p className="analysis-muted">No other recognized speaker shares a scene with {character?.name ?? 'this draft’s characters'}.</p>}</section>
        <section className="analysis-scenes" aria-label="Analyzed draft scenes"><div className="analysis-section-heading"><h3>Scenes in this draft</h3><span>Exact source ranges · {analysis.lineCount} draft lines</span></div>{analysis.preambleCharacters > 0 && <p className="analysis-muted">Title and opening material before the first heading are excluded from scene dialogue analysis.</p>}<ol>{analysis.scenes.slice(0, sceneLimit).map(scene => <li key={scene.id}><span className="analysis-scene-number">{String(scene.index).padStart(2, '0')}</span><div><h4>{sceneLink(scene.index, scene.heading)}</h4><p>Lines {scene.startLine}–{scene.endLine} · {scene.dialogueLines} dialogue lines · {scene.dialogueWords} dialogue words</p><p>{scene.speakingCharacters.length ? scene.speakingCharacters.join(', ') : 'No recognized dialogue'}</p><details><summary>Read this exact scene</summary><pre>{scene.text}</pre><p className="analysis-muted">Draft text range [{scene.start}, {scene.end}). These draft positions do not change the retained film’s scene mapping.</p></details></div></li>)}</ol>{analysis.scenes.length > sceneLimit && <button type="button" className="analysis-link" onClick={() => setSceneLimit(value => value + PAGE)}>Show more scenes ({analysis.scenes.length - sceneLimit})</button>}</section>
      </>}
    </>}
  </section>;
}
