import { useMemo, useState } from 'react';
import { ArrowUpRight, Download, Search } from 'lucide-react';
import { downloadLocalBlob } from './localDownload';
import { BIBLE_CHAPTERS, bibleReviewLabel, bibleSceneLabel, storyBibleManuscript, storyBibleMarkdown } from './storyBibleManuscript';
import { activeWorldNeeds, worldNeedBudgetTarget } from './worldProductionModel';
import type { StoryBiblePanelProps } from './StoryBiblePanel';
import type { UniverseCitation, UniverseEntity } from './universeApi';

type Props = StoryBiblePanelProps & { onOpenEntry: (entity: UniverseEntity) => void };
const anchor = (id: string) => `bible-entry-${encodeURIComponent(id)}`;

export default function StoryBibleBookView({ model, projectTitle, scenes = [], onOpenEntry, onEditProfile, onProposeClaim, onReadSource, onScene, onContinuity, onPlanProduction, onOpenBudget }: Props) {
  const book = useMemo(() => storyBibleManuscript(model), [model]);
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('all'), [notice, setNotice] = useState('');
  const names = new Map(model.entities.map(entity => [entity.id, entity.name]));
  const needle = query.trim().toLocaleLowerCase();
  const visible = book.entries.filter(entry => (!needle || [entry.entity.name, entry.entity.summary, ...entry.sections.flatMap(section => section.fields.map(field => field.text)), ...entry.claims.flatMap(claim => [claim.data.title, claim.data.body])].join('\n').toLocaleLowerCase().includes(needle)) && (filter === 'all' || filter === 'undeveloped' ? filter === 'all' || !entry.profile : entry.entity.type === filter));
  const sourceButtons = (citations: UniverseCitation[]) => citations.length > 0 && <div className="bible-manuscript-sources">{citations.map((citation, index) => <button type="button" key={index} onClick={() => onReadSource(citation)}>{citation.label}{citation.pageNumber !== null ? ` · p${citation.pageNumber}` : ''}<ArrowUpRight size={12}/></button>)}</div>;
  function exportBook() {
    try {
      const title = projectTitle || model.projectId;
      downloadLocalBlob(new Blob([storyBibleMarkdown(model, title, scenes)], { type: 'text/markdown;charset=utf-8' }), `${title.replace(/[^a-z0-9._-]+/gi, '-').slice(0, 100) || 'Project'}-story-bible.md`);
      setNotice('Full bible exported from saved records, including every entry and its source register.');
    } catch { setNotice('The export could not start. Your saved bible has not changed.'); }
  }
  return <section className="bible-manuscript" aria-label="Full story bible">
    <header className="bible-manuscript-title"><div><span>Working manuscript</span><h2>{projectTitle || model.projectId}</h2><p>{book.entries.length} entries · {book.profiles} authored profiles · {book.claims} statements · {model.links.length} relationships</p></div><button type="button" onClick={exportBook}><Download size={14}/>Export full bible</button></header>
    <p className="bible-muted">Read the project as one document. Changes belong to the entry, profile, relationship or continuity record that owns them. Export includes all saved entries and evidence; search filters and unsaved edits do not alter it.</p>
    {notice && <p role="status" className="bible-manuscript-notice">{notice}</p>}
    <nav className="bible-manuscript-chapters" aria-label="Bible chapters">{BIBLE_CHAPTERS.map(chapter => <a key={chapter.type} href={`#bible-chapter-${chapter.type}`}>{chapter.title} <span>{book.entries.filter(entry => entry.entity.type === chapter.type).length}</span></a>)}<a href="#bible-relationships">Relationships</a><a href="#bible-continuity">Continuity</a><a href="#bible-production">Production needs</a><a href="#bible-questions">Open questions</a></nav>
    <div className="bible-manuscript-find"><label><Search size={14}/><input aria-label="Search story bible" type="search" placeholder="Search names, profiles and statements" value={query} onChange={event => setQuery(event.target.value)}/></label><label>Show<select aria-label="Story bible manuscript filter" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All entries</option><option value="undeveloped">Profiles to develop</option>{BIBLE_CHAPTERS.map(chapter => <option key={chapter.type} value={chapter.type}>{chapter.title}</option>)}</select></label><small>{visible.length} entries shown</small></div>
    {model.storylines.length > 0 && <section className="bible-manuscript-groupings"><h3>Story groupings</h3><p>{model.storylines.map(story => story.title).join(' · ')}</p><small>Source title groupings. Shared chronology and identity are not inferred.</small></section>}
    {BIBLE_CHAPTERS.map(chapter => {
      const entries = visible.filter(entry => entry.entity.type === chapter.type);
      if (filter !== 'all' && !entries.length) return null;
      return <section key={chapter.type} id={`bible-chapter-${chapter.type}`} className="bible-manuscript-chapter"><h3>{chapter.title}<span>{entries.length}</span></h3>{!entries.length ? <p className="bible-muted">{needle ? 'No entries match this search.' : `No ${chapter.title.toLocaleLowerCase()} recorded.`}</p> : entries.map(({ entity, profile, sections, claims, agent }) => <article id={anchor(entity.id)} className="bible-manuscript-entry" key={entity.id}>
        <header><div><h4>{entity.name}</h4><small>{bibleReviewLabel(entity.review)} · {entity.origin.replace(/_/g, ' ').toLocaleLowerCase()}</small></div><div className="bible-manuscript-actions"><button type="button" onClick={() => onOpenEntry(entity)}>Open entry<ArrowUpRight size={12}/></button>{onEditProfile && <button type="button" onClick={() => onEditProfile(entity)}>{profile ? 'Edit profile' : 'Develop profile'}</button>}<button type="button" onClick={() => onProposeClaim(entity)}>Add statement</button></div></header>
        <p className="bible-body">{entity.summary || 'No description recorded.'}</p>{sourceButtons(entity.citations)}
        {entity.sceneIds.length > 0 && <div className="bible-manuscript-scenes">{entity.sceneIds.map(id => <button type="button" key={id} onClick={() => onScene(id)}>{bibleSceneLabel(id, scenes)}</button>)}</div>}
        {profile ? <div className="bible-manuscript-profile"><p className="bible-muted">Author profile · {bibleReviewLabel(profile.data.review)} · Saved v{profile.version}</p>{sections.map(section => <section key={section.id}><h5>{section.label}</h5><dl>{section.fields.map(field => <div key={field.id}><dt>{field.label}</dt><dd>{field.text}</dd></div>)}</dl></section>)}{sourceButtons(profile.data.citations)}</div> : <p className="bible-manuscript-missing">Profile not developed. Add the character, world, narrative or visual intentions that matter to this project.</p>}
        {claims.map(claim => <section className="bible-manuscript-statement" key={claim.id}><h5>{claim.data.title}<small>{bibleReviewLabel(claim.data.review)} · v{claim.version}</small></h5><p className="bible-body">{claim.data.body}</p>{sourceButtons(claim.data.citations)}</section>)}
        {agent && <section className="bible-manuscript-statement"><h5>Character perspective<small>{bibleReviewLabel(agent.data.review)} · v{agent.version}</small></h5><p className="bible-muted">Supplied character perspective, distinct from world facts.</p>{([['Goals', agent.data.goals], ['Boundaries', agent.data.boundaries], ['Observations', agent.data.observations], ['Beliefs', agent.data.beliefs], ['Memories', agent.data.memories]] as const).map(([label, values]) => values.length > 0 && <div key={label}><strong>{label}</strong><ul>{values.map((value, index) => <li className="bible-body" key={index}>{value}</li>)}</ul></div>)}{agent.data.voice && <p className="bible-body">Voice: {agent.data.voice}</p>}{sourceButtons(agent.data.citations)}</section>}
      </article>)}</section>;
    })}
    <section id="bible-relationships" className="bible-manuscript-chapter"><h3>Relationships<span>{model.links.length}</span></h3>{model.links.map(link => <article className="bible-manuscript-statement" key={link.id}><h4>{names.get(link.fromEntityId) ?? link.fromEntityId} → {names.get(link.toEntityId) ?? link.toEntityId}</h4><small>{link.relation.replace(/_/g, ' ')} · {bibleReviewLabel(link.review)}</small><p className="bible-body">{link.label}</p>{link.relation === 'possible_alias' && <p className="bible-muted">Possible alias. Both identities remain separate.</p>}{sourceButtons(link.citations)}<button type="button" onClick={() => { const entity = model.entities.find(item => item.id === link.fromEntityId); if (entity) onOpenEntry(entity); }}>Review relationship in entry</button></article>)}{!model.links.length && <p className="bible-muted">No relationships recorded. Open an entry to connect it to another.</p>}</section>
    <section id="bible-continuity" className="bible-manuscript-chapter"><header><h3>Continuity & identities</h3>{onContinuity && model.entities[0] && <button type="button" onClick={() => onContinuity(model.entities[0])}>Edit continuity</button>}</header>{book.continuity ? <><p className="bible-muted">Plan · {bibleReviewLabel(book.continuity.data.review)} · Saved v{book.continuity.version}. Listed event order is not a chronology.</p>{book.continuity.data.events.map(event => <article key={event.id} className="bible-manuscript-statement"><h4>{event.title}</h4><small>{bibleReviewLabel(event.review)} · {event.timeLabel || 'Time unspecified'}</small><p className="bible-body">{event.description}</p><p className="bible-muted">{event.entityIds.map(id => names.get(id) ?? id).join(' · ')}</p><p className="bible-muted">Before: {event.beforeEventIds.map(id => book.continuity?.data.events.find(item => item.id === id)?.title ?? id).join(' · ') || 'No ordering recorded'}</p></article>)}{book.continuity.data.aliases.map(alias => <article className="bible-manuscript-statement" key={alias.id}><h4>{names.get(alias.fromEntityId)} ↔ {names.get(alias.toEntityId)}</h4><small>{alias.decision.replace(/_/g, ' ')} · {bibleReviewLabel(alias.review)}</small><p className="bible-body">{alias.note}</p></article>)}{Boolean(book.order?.cycleIds.length || book.order?.missing.length || book.conflicts.length) && <p className="bible-limit">Continuity needs attention: {book.order?.cycleIds.length ?? 0} events in cycles, {book.order?.missing.length ?? 0} missing links, {book.conflicts.length} identity conflicts.</p>}</> : <p className="bible-muted">No continuity plan saved. Record event order, time and identity decisions in Continuity.</p>}</section>
    <section id="bible-production" className="bible-manuscript-chapter"><h3>Production needs<span>{book.needs}</span></h3>{book.entries.filter(entry => entry.production).map(({ entity, production }) => <article key={entity.id} className="bible-manuscript-statement"><header><h4>{entity.name}</h4>{onPlanProduction && <button type="button" onClick={() => onPlanProduction(entity)}>Edit needs</button>}</header><p className="bible-muted">Plan · {bibleReviewLabel(production!.data.review)} · v{production!.version}</p>{production!.data.needs.map(need => <section key={need.id}><h5>{need.label}<small>{need.department} · {bibleReviewLabel(need.review)}</small></h5><p className="bible-body">{need.description}</p><p className="bible-muted">{need.sceneIds.map(id => bibleSceneLabel(id, scenes)).join(' · ') || 'Project-wide; scenes not assigned'}</p>{onOpenBudget && activeWorldNeeds(production).some(item => item.id === need.id) && <button type="button" onClick={() => onOpenBudget(worldNeedBudgetTarget(entity.id, need.id))}>Budget this need<ArrowUpRight size={12}/></button>}</section>)}</article>)}{!book.needs && <p className="bible-muted">Open an entry to plan its performance, location, wardrobe, props, effects or sound needs.</p>}</section>
    <section id="bible-questions" className="bible-manuscript-chapter"><h3>Open questions<span>{model.questions.length}</span></h3>{model.questions.map(question => <article key={question.id} className="bible-manuscript-statement"><p className="bible-body">{question.text}</p>{sourceButtons(question.citations)}</article>)}{!model.questions.length && <p className="bible-muted">No explicit questions recorded. This does not establish completeness.</p>}</section>
    <footer className="bible-manuscript-footer">{book.citations.length} distinct source citations accompany the full Markdown export. Source revision {model.sourceHash.slice(0, 12)} · Catalog {model.basisHash.slice(0, 12)}</footer>
  </section>;
}
