import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Scale, Gavel, FileText, BookOpen, AlertTriangle, ChevronDown, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";

const preAmble = `Before 2023, U.S. copyright law had no framework for AI-generated works. The Copyright Act assumed human authorship without explicitly addressing machine creativity. No court had directly ruled on whether AI could be an "author." Fair use doctrine had never been tested against large-scale AI training on copyrighted datasets. The legal landscape was silent — and that silence left writers, studios, and AI companies operating in a gray zone.`;

interface TimelineItem {
  title: string;
  description: string;
  citation: string;
  court: string;
  faqLinks: { label: string; hash: string }[];
}

const timelineEvents: {
  year: string;
  icon: typeof Gavel;
  items: TimelineItem[];
}[] = [
  {
    year: "2023",
    icon: Gavel,
    items: [
      {
        title: "Thaler v. Perlmutter",
        description:
          "A federal court rules that copyright requires human authorship. An AI system cannot be listed as the author of a work. This is the first direct judicial statement on AI and copyright ownership.",
        citation: "Thaler v. Perlmutter, No. 1:22-cv-01564 (D.D.C. Aug. 18, 2023)",
        court: "U.S. District Court for the District of Columbia",
        faqLinks: [
          { label: "Who owns AI-generated screenplays?", hash: "#legal-ownership" },
          { label: "Human authorship requirements", hash: "#human-authorship" },
        ],
      },
    ],
  },
  {
    year: "2024",
    icon: FileText,
    items: [
      {
        title: "U.S. Copyright Office Reports",
        description:
          "The Copyright Office issues formal guidance: AI-generated material alone is not copyrightable. Works containing both human and AI elements may qualify, but only the human-authored portions receive protection. Human contribution must be identifiable.",
        citation: "U.S. Copyright Office, Copyright Registration Guidance: Works Containing Material Generated by Artificial Intelligence, 89 Fed. Reg. 16,190 (Mar. 6, 2024)",
        court: "U.S. Copyright Office (Administrative Guidance)",
        faqLinks: [
          { label: "How does hybrid authorship affect copyright?", hash: "#hybrid-authorship" },
          { label: "AI disclosure requirements", hash: "#ai-disclosure" },
        ],
      },
    ],
  },
  {
    year: "2025",
    icon: BookOpen,
    items: [
      {
        title: "Thomson Reuters v. ROSS Intelligence",
        description:
          "Courts examine whether AI training on copyrighted legal materials constitutes fair use. The case signals that training data provenance will face increasing legal scrutiny.",
        citation: "Thomson Reuters Enterprise Centre GmbH v. ROSS Intelligence Inc., No. 1:20-cv-00613 (D. Del. 2025)",
        court: "U.S. District Court for the District of Delaware",
        faqLinks: [
          { label: "Training data & fair use", hash: "#fair-use" },
          { label: "Dataset contamination risks", hash: "#dataset-contamination" },
        ],
      },
      {
        title: "Authors Guild v. Anthropic Settlement",
        description:
          "Settlement valued at approximately $1.5 billion. Establishes that training data provenance is a major economic and legal factor. The publishing industry demands transparency about what materials influence AI outputs.",
        citation: "Authors Guild et al. v. Anthropic, PBC, No. 1:23-cv-08292 (S.D.N.Y. 2025, settled)",
        court: "U.S. District Court for the Southern District of New York",
        faqLinks: [
          { label: "Derivative similarity risks", hash: "#derivative-similarity" },
          { label: "How provenance protects writers", hash: "#provenance" },
        ],
      },
      {
        title: "Bartz v. Anthropic",
        description:
          "Court scrutinizes fair use defense for LLM training, emphasizing market harm as the pivotal factor. The ruling signals that generative AI outputs competing with source material undermine fair use claims.",
        citation: "Bartz v. Anthropic, PBC (N.D. Cal. 2025)",
        court: "U.S. District Court for the Northern District of California",
        faqLinks: [
          { label: "Training data & fair use", hash: "#fair-use" },
          { label: "Output infringement risks", hash: "#output-infringement" },
        ],
      },
      {
        title: "Kadrey v. Meta Platforms",
        description:
          "Authors' claims against Meta's LLM training survive dismissal. The court finds that market harm from AI-generated outputs substituting for original works is a viable theory, strengthening derivative similarity arguments.",
        citation: "Kadrey v. Meta Platforms, Inc. (N.D. Cal. 2025)",
        court: "U.S. District Court for the Northern District of California",
        faqLinks: [
          { label: "Derivative similarity risks", hash: "#derivative-similarity" },
          { label: "Market harm & AI outputs", hash: "#output-infringement" },
        ],
      },
      {
        title: "GEMA v. OpenAI (Munich)",
        description:
          "German music rights society GEMA challenges OpenAI's training practices under EU copyright law. The Munich Regional Court examines whether AI training constitutes 'making available' copyrighted works — a first in EU jurisdiction.",
        citation: "GEMA v. OpenAI, LG München I (2025)",
        court: "Munich Regional Court I (Landgericht München I)",
        faqLinks: [
          { label: "Training data & fair use", hash: "#fair-use" },
          { label: "EU copyright implications", hash: "#eu-copyright" },
        ],
      },
    ],
  },
  {
    year: "2026",
    icon: AlertTriangle,
    items: [
      {
        title: "Thaler Appeal Denied by Supreme Court",
        description:
          "The U.S. Supreme Court declines to review the Thaler ruling, leaving intact the principle that copyright requires human authorship. Fully autonomous AI outputs remain unprotectable.",
        citation: "Thaler v. Perlmutter, No. 23-1170, cert. denied (U.S. Jan. 13, 2026)",
        court: "Supreme Court of the United States",
        faqLinks: [
          { label: "What does this mean for AI-only scripts?", hash: "#ai-only" },
          { label: "Human authorship requirements", hash: "#human-authorship" },
        ],
      },
      {
        title: "Concord Music Group v. Anthropic (Ongoing)",
        description:
          "Music publishers argue that AI outputs can compete with and unlawfully reproduce copyrighted material. Creative similarity is becoming legally measurable, raising stakes for all AI-assisted creative work.",
        citation: "Concord Music Group, Inc. v. Anthropic, PBC, No. 3:23-cv-01092 (M.D. Tenn. 2026, pending)",
        court: "U.S. District Court for the Middle District of Tennessee",
        faqLinks: [
          { label: "Output infringement risks", hash: "#output-infringement" },
          { label: "Derivative similarity risks", hash: "#derivative-similarity" },
        ],
      },
      {
        title: "Stober & Dornis: GenAI Training ≠ TDM",
        description:
          "Landmark interdisciplinary paper establishes that generative AI training fundamentally differs from Text and Data Mining (TDM). GenAI replicates the full distribution of training data to produce competing outputs — not just extracting patterns. EU TDM exceptions and US fair use may not cover this process. The paper proposes a tiered documentation framework for training data provenance.",
        citation: "Stober & Dornis, 'Generative AI Training and Copyright Law: An Interdisciplinary Analysis,' arXiv:2502.15858 (2026)",
        court: "Scholarly Publication (Interdisciplinary Legal-Technical Analysis)",
        faqLinks: [
          { label: "GenAI Training vs. TDM", hash: "#genai-tdm" },
          { label: "Memorization & regurgitation risk", hash: "#memorization-risk" },
          { label: "How provenance protects writers", hash: "#provenance" },
        ],
      },
    ],
  },
];

export default function AILawTimeline() {
  const [expanded, setExpanded] = useState<string | null>(null);

  const toggle = (key: string) =>
    setExpanded((prev) => (prev === key ? null : key));

  return (
    <div className="max-w-2xl">
      {/* Pre-2023 summary */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="mb-12 p-5 rounded-xl border border-border/50 bg-card/50"
      >
        <div className="flex items-center gap-2 mb-3">
          <Scale className="h-4 w-4 text-primary" />
          <h4 className="font-display text-sm font-bold text-foreground">Before 2023</h4>
        </div>
        <p className="text-sm text-muted-foreground leading-relaxed">{preAmble}</p>
      </motion.div>

      {/* Timeline */}
      <div className="relative pl-8">
        {/* Vertical line */}
        <div className="absolute left-[15px] top-0 bottom-0 w-px bg-border" />

        {timelineEvents.map((event, ei) => (
          <motion.div
            key={event.year}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, margin: "-40px" }}
            transition={{ duration: 0.5, delay: ei * 0.1 }}
            className="relative mb-10 last:mb-0"
          >
            {/* Year marker */}
            <div className="absolute -left-8 flex items-center justify-center w-[30px] h-[30px] rounded-full bg-primary text-primary-foreground">
              <event.icon className="h-3.5 w-3.5" />
            </div>
            <span className="inline-block font-mono text-xs font-bold tracking-wider text-primary mb-3">
              {event.year}
            </span>

            <div className="space-y-3">
              {event.items.map((item, ii) => {
                const key = `${event.year}-${ii}`;
                const isOpen = expanded === key;

                return (
                  <div key={ii} className="rounded-lg border border-border/50 bg-card/50 overflow-hidden">
                    <button
                      onClick={() => toggle(key)}
                      className="w-full text-left p-4 flex items-start gap-3 hover:bg-muted/30 transition-colors cursor-pointer"
                    >
                      <div className="flex-1 min-w-0">
                        <h5 className="font-display text-sm font-semibold text-foreground mb-1.5">
                          {item.title}
                        </h5>
                        <p className="text-xs text-muted-foreground leading-relaxed">
                          {item.description}
                        </p>
                      </div>
                      <ChevronDown
                        className={`h-4 w-4 shrink-0 text-muted-foreground mt-0.5 transition-transform duration-200 ${isOpen ? "rotate-180" : ""}`}
                      />
                    </button>

                    <AnimatePresence>
                      {isOpen && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.2 }}
                          className="overflow-hidden"
                        >
                          <div className="px-4 pb-4 pt-0 border-t border-border/30 space-y-3">
                            <div className="pt-3 space-y-2">
                              <div>
                                <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">Citation</span>
                                <p className="text-xs text-foreground/80 font-mono leading-relaxed mt-0.5">
                                  {item.citation}
                                </p>
                              </div>
                              <div>
                                <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">Court</span>
                                <p className="text-xs text-foreground/80 mt-0.5">{item.court}</p>
                              </div>
                            </div>

                            {item.faqLinks.length > 0 && (
                              <div>
                                <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">Related FAQ</span>
                                <div className="flex flex-wrap gap-1.5 mt-1.5">
                                  {item.faqLinks.map((faq) => (
                                    <Link key={faq.hash} to={`/faq${faq.hash}`}>
                                      <Badge
                                        variant="outline"
                                        className="text-[10px] font-mono gap-1 hover:bg-primary/10 hover:border-primary/30 transition-colors cursor-pointer"
                                      >
                                        <ExternalLink className="h-2.5 w-2.5" />
                                        {faq.label}
                                      </Badge>
                                    </Link>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })}
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
