/**
 * JudgingTransparency — explains how evaluation works, what AI does and doesn't do.
 * Static, non-technical, credibility-building content.
 */
import { Shield, Brain, Eye, FileCheck, AlertTriangle, Info } from "lucide-react";
import { Separator } from "@/components/ui/separator";
import { AnalyticsAccessBadge } from "@/components/competition/AnalyticsAccessBadge";

function TransparencySection({ icon: Icon, title, items }: { icon: any; title: string; items: string[] }) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center gap-2">
        <Icon className="h-3.5 w-3.5 text-primary" />
        <p className="text-xs font-display font-semibold text-foreground">{title}</p>
      </div>
      <ul className="space-y-1 pl-6">
        {items.map((item, i) => (
          <li key={i} className="text-xs text-muted-foreground list-disc">{item}</li>
        ))}
      </ul>
    </div>
  );
}

export default function JudgingTransparency() {
  return (
    <div className="rounded-xl border border-border/50 bg-card/80 p-5 space-y-4">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-2">
          <Eye className="h-5 w-5 text-primary" />
          <h3 className="font-display text-sm font-bold tracking-tight">How Evaluation Works</h3>
        </div>
        <AnalyticsAccessBadge />
      </div>

      <p className="text-xs text-muted-foreground leading-relaxed">
        Every screenplay submitted to the platform goes through a structured evaluation pipeline.
        This section explains what the system does, what it doesn't do, and where human oversight exists.
      </p>

      <Separator className="opacity-50" />

      <TransparencySection
        icon={Brain}
        title="What AI is used for"
        items={[
          "Analyzing screenplays against a structured rubric to surface signals across originality, structure, character, dialogue, theme, emotion, and format.",
          "Generating stability observations across multiple evaluation passes.",
          "Detecting voice drift patterns and stylistic consistency across versions.",
          "Producing provenance artifacts that trace authorship signals.",
          "Generating evidence bundles for export and review.",
        ]}
      />

      <TransparencySection
        icon={AlertTriangle}
        title="What AI is not used for"
        items={[
          "Making final competition decisions — ranking logic is deterministic and based on stored scores.",
          "Modifying or rewriting submitted screenplays during evaluation.",
          "Accessing user data beyond the submitted screenplay and its metadata.",
          "Replacing human review — flagged entries are surfaced to administrators.",
        ]}
      />

      <TransparencySection
        icon={Shield}
        title="Where human oversight exists"
        items={[
          "Administrators can review flagged entries and re-run evaluations.",
          "Competition configurations (rubric weights, model selection) are set by humans.",
          "Disputed results can be escalated for manual review.",
          "All AI decisions are logged in the governance audit trail.",
        ]}
      />

      <TransparencySection
        icon={FileCheck}
        title="What signals influence scoring"
        items={[
          "Rubric-defined observation dimensions: originality, structure, character depth, dialogue, theme, emotion, format adherence.",
          "Signal consistency across multiple analysis passes.",
          "Script quotient signals when available (audience, market, franchise, production).",
        ]}
      />

      <TransparencySection
        icon={Info}
        title="What does not influence scoring"
        items={[
          "Author identity or profile information.",
          "Token balance or subscription tier.",
          "Submission order or timing.",
          "Previous scores on other entries.",
        ]}
      />

      <Separator className="opacity-50" />
      <p className="text-[10px] text-muted-foreground">
        Evaluation results are analytical signals generated by AI models. They are not definitive artistic judgments.
        The platform presents these signals transparently so writers and reviewers can make informed assessments.
      </p>
    </div>
  );
}
