// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-entries.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/roles.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";

// src/lib/mcp/accessDenial.ts
async function logMcpAccessDenial(ctx, event, opts) {
  if (process.env.VITEST) return;
  const url = process.env.SUPABASE_URL;
  if (!url) return;
  const token = ctx.isAuthenticated?.() ? ctx.getToken?.() : void 0;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY ?? "";
  try {
    void fetch(`${url}/functions/v1/log-access-denial`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        apikey: anon,
        authorization: `Bearer ${token ?? anon}`
      },
      body: JSON.stringify({
        event_type: event,
        resource: opts.tool,
        reason: opts.reason,
        details: {
          ...opts.details ?? {},
          surface: "mcp",
          tool: opts.tool,
          user_id: ctx.isAuthenticated?.() ? ctx.getUserId?.() : null,
          client_id: ctx.getClientId?.() ?? null
        }
      })
    }).catch(() => {
    });
  } catch {
  }
}

// src/lib/mcp/roles.ts
function deny(text) {
  return { isError: true, content: [{ type: "text", text }] };
}
async function requireEntrant(ctx, opts = {}) {
  if (!ctx.isAuthenticated()) {
    void logMcpAccessDenial(ctx, "mcp_entrant_gate", {
      tool: opts.tool ?? "mcp_tool",
      reason: "not authenticated"
    });
    return deny("Not authenticated. Sign in from your assistant to use writer tools.");
  }
  return null;
}

// src/lib/mcp/tools/list-my-entries.ts
function supabaseForUser(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_entries_default = defineTool({
  name: "list_my_entries",
  title: "List my screenplay entries",
  description: "List the signed-in user's screenplay entries (submissions) with title, status, genre, and creation date.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Max entries to return."),
    status: z.string().optional().describe("Optional status filter (e.g. 'submitted', 'draft').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    const denied = await requireEntrant(ctx, { tool: "list_my_entries" });
    if (denied) return denied;
    let query = supabaseForUser(ctx).from("entries").select("id, title, genre, logline, status, length_category, page_count, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-entry-scorecard.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_entry_scorecard_default = defineTool2({
  name: "get_entry_scorecard",
  title: "Get entry scorecard",
  description: "Fetch a screenplay entry the signed-in user can read, including its latest scores (narrative, character, dialogue, structure, total, feedback).",
  inputSchema: {
    entry_id: z2.string().uuid().describe("The entry id to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ entry_id }, ctx) => {
    const denied = await requireEntrant(ctx, { tool: "get_entry_scorecard" });
    if (denied) return denied;
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("entries").select(
      "id, title, genre, logline, status, length_category, page_count, author, created_at, scores(total_score, narrative, character_score, dialogue, structure, theme, emotion, feedback, created_at, superseded_at)"
    ).eq("id", entry_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Entry not found or not accessible." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-competitions.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_competitions_default = defineTool3({
  name: "list_competitions",
  title: "List active competitions",
  description: "List active screenplay competitions on the platform with title, length category, deadline, and prize summary.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Max competitions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("competitions").select("id, title, length_category, status, submission_deadline, prize_pool, created_at").eq("status", "active").order("submission_deadline", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { competitions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xuffmufumgdrsawhryex";
var mcp_default = defineMcp({
  name: "caniscreenwrite-mcp",
  title: "CanIScreenwrite MCP",
  version: "0.1.0",
  instructions: "Tools for CanIScreenwrite \u2014 a screenwriting competition and evaluation platform. Use `list_my_entries` and `get_entry_scorecard` to read the signed-in writer's submissions and AI scores, and `list_competitions` to see active competitions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_entries_default, get_entry_scorecard_default, list_competitions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
